# Generated by Django 5.2.10 on 2026-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_technician_dispatchjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchjob',
            new_name='staff_dispa_status_97a1b5_idx',
            old_name='staff_dispatchjob_status_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchjob',
            new_name='staff_dispa_assigne_abcca8_idx',
            old_name='staff_dispatchjob_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchjob',
            new_name='staff_dispa_schedul_868b1f_idx',
            old_name='staff_dispatchjob_sched_idx',
        ),
        migrations.AlterField(
            model_name='dispatchjob',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes'),
        ),
    ]
