# Generated by Django 4.2.7 on 2026-01-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_plan_options_remove_plan_auto_renew_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconnection',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_connections', to='billing.plan'),
        ),
    ]
