# Generated by Django 4.2.7 on 2026-01-10 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_alter_plan_options_remove_plan_auto_renew_and_more'),
        ('customers', '0002_serviceconnection_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconnection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Connection', 'verbose_name_plural': 'Service Connections'},
        ),
        migrations.RemoveField(
            model_name='serviceconnection',
            name='service_plan',
        ),
        migrations.AddField(
            model_name='serviceconnection',
            name='auth_connection_type',
            field=models.CharField(blank=True, choices=[('HOTSPOT', 'Hotspot'), ('PPPOE', 'PPPoE'), ('STATIC', 'Static IP'), ('DYNAMIC', 'Dynamic IP'), ('OTHER', 'Other')], default='PPPOE', help_text='PPPoE, Hotspot, Static IP etc. - used for analytics', max_length=20, verbose_name='Authentication Type'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activation Date'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='auto_renew',
            field=models.BooleanField(default=True, verbose_name='Auto Renew'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='connection_type',
            field=models.CharField(choices=[('FIBER', 'Fiber Optic'), ('WIRELESS', 'Wireless'), ('COPPER', 'Copper (DSL)'), ('SATELLITE', 'Satellite')], default='FIBER', max_length=30, verbose_name='Connection Medium'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='contract_period',
            field=models.PositiveIntegerField(default=12, help_text='Contract period in months (0 = no contract)', verbose_name='Contract Period (months)'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_connections', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='data_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Data cap in GB (null = unlimited)', null=True, verbose_name='Data Cap (GB)'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='download_speed',
            field=models.PositiveIntegerField(help_text='Provisioned download speed in Mbps', verbose_name='Download Speed (Mbps)'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='installation_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_installations', to='customers.customeraddress', verbose_name='Installation Address'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='installation_notes',
            field=models.TextField(blank=True, verbose_name='Installation Notes'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_services', to=settings.AUTH_USER_MODEL, verbose_name='Installed By'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Price (KES)'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='ont_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='ONT Model'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='ont_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='ONT Serial'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_connections', to='billing.plan', verbose_name='Assigned Plan'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='prorated_billing',
            field=models.BooleanField(default=True, verbose_name='Prorated Billing'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='qos_profile',
            field=models.CharField(blank=True, max_length=50, verbose_name='QoS Profile'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='router_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Router Model'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='router_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Router Serial'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='service_type',
            field=models.CharField(choices=[('INTERNET', 'Internet Service'), ('VOIP', 'VoIP Service'), ('IPTV', 'IP TV'), ('DEDICATED', 'Dedicated Line'), ('WIFI', 'WiFi Hotspot'), ('VPN', 'VPN Service'), ('COLOCATION', 'Colocation')], default='INTERNET', max_length=30, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Setup Fee (KES)'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='suspension_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspension Date'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='termination_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termination Date'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_connections', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='upload_speed',
            field=models.PositiveIntegerField(help_text='Provisioned upload speed in Mbps', verbose_name='Upload Speed (Mbps)'),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='vlan_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='VLAN ID'),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['status'], name='customers_s_status_3cb4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['customer', 'status'], name='customers_s_custome_81fe42_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['plan', 'status'], name='customers_s_plan_id_e4ab85_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['auth_connection_type'], name='customers_s_auth_co_dbae82_idx'),
        ),
    ]
