# Generated by Django 5.2.10 on 2026-04-08 14:41

import apps.customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_hotspotclient_hotspotclientdevice_mpesaconfiguration_and_more'),
        ('customers', '0002_make_id_number_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconnection',
            name='billing_account_number',
            field=models.CharField(db_index=True, default=apps.customers.models.generate_billing_account_number, help_text='The Account Number the customer uses when paying via Paybill. Usually 6-10 alphanumeric characters.', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='serviceconnection',
            name='mpesa_account_number',
            field=models.CharField(blank=True, db_index=True, help_text='Alternative account number specifically for M-Pesa payments (if different from billing_account_number)', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceconnection',
            name='paybill_account_number',
            field=models.CharField(blank=True, db_index=True, help_text='Account number for Paybill payments (usually customer code or billing_account_number)', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['billing_account_number'], name='customers_s_billing_9454da_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['mpesa_account_number'], name='customers_s_mpesa_a_c3e123_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceconnection',
            index=models.Index(fields=['paybill_account_number'], name='customers_s_paybill_db4f4e_idx'),
        ),
    ]
