# Generated by Django 5.2.10 on 2026-05-29 23:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_serviceconnection_billing_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, help_text="Customer's physical location or area (e.g., Westlands, Nairobi)", max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='prepaid_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unallocated credit from partial or overpayments', max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='billing_account_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The Account Number the customer uses when paying via Paybill. Usually 6-10 alphanumeric characters.', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['location'], name='customers_c_locatio_b2f73c_idx'),
        ),
    ]
