# Generated by Django 4.2.7 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_id_number'),
        ('customers', '0003_serviceconnection_billing_account_number_and_more'),
    ]

    operations = [
    ]
