# Generated by Django 5.2.10 on 2026-04-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('vonage', 'Vonage (Nexmo)'), ('infobip', 'Infobip'), ('beem', 'Beem Africa'), ('advanta', 'Advanta SMS'), ('hubtel', 'Hubtel')], max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('sender_id', models.CharField(blank=True, default='', max_length=20)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('auto_payment_confirmation', models.BooleanField(default=True)),
                ('auto_expiry_reminder', models.BooleanField(default=True)),
                ('auto_welcome_message', models.BooleanField(default=True)),
                ('auto_service_suspension', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Gateway Config',
                'verbose_name_plural': 'SMS Gateway Configs',
            },
        ),
    ]
