# Generated by Django 5.2.10 on 2026-05-29 23:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_sms_gateway_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_inbuilt_system', models.BooleanField(default=False, help_text="If True, use Netily's built-in Bytewave gateway instead of custom provider")),
                ('hotspot_new_subscription', models.BooleanField(default=False, help_text='SMS when a hotspot user makes a new purchase')),
                ('hotspot_welcome', models.BooleanField(default=False, help_text='Welcome SMS when a hotspot session activates')),
                ('hotspot_session_expiry', models.BooleanField(default=False, help_text='Notify hotspot user when their session is about to expire')),
                ('hotspot_expiry_minutes_before', models.PositiveIntegerField(default=15, help_text='How many minutes before expiry to send the hotspot reminder')),
                ('hotspot_payment_failed', models.BooleanField(default=False, help_text='Notify when hotspot STK push payment fails')),
                ('hotspot_session_expired', models.BooleanField(default=False, help_text='Notify when hotspot session has fully expired')),
                ('pppoe_welcome', models.BooleanField(default=False, help_text='Welcome SMS when a new PPPoE/Static customer is activated')),
                ('pppoe_payment_confirmation', models.BooleanField(default=False, help_text='SMS confirmation after a PPPoE payment is received')),
                ('pppoe_expiry_reminder', models.BooleanField(default=False, help_text='Remind PPPoE customer before subscription expires')),
                ('pppoe_expiry_days_before', models.PositiveIntegerField(default=4, help_text='How many days before expiry to send the PPPoE reminder')),
                ('pppoe_service_suspended', models.BooleanField(default=False, help_text='Notify when PPPoE service is suspended')),
                ('pppoe_service_resumed', models.BooleanField(default=False, help_text='Notify when PPPoE service is restored')),
                ('pppoe_plan_changed', models.BooleanField(default=False, help_text='Notify customer when their plan is changed')),
                ('pppoe_renewal_confirmation', models.BooleanField(default=False, help_text='Confirm successful subscription renewal')),
                ('pppoe_new_subscription', models.BooleanField(default=False, help_text='SMS when admin creates a new PPPoE subscription for a customer')),
                ('system_router_offline', models.BooleanField(default=False, help_text='Send an SMS alert when a router goes offline')),
                ('system_alert_phone', models.CharField(blank=True, default='', help_text='Phone number to receive system alerts (e.g. +2547...)', max_length=20)),
                ('router_offline_enabled', models.BooleanField(default=False, help_text='Send SMS when any MikroTik router goes offline')),
                ('router_offline_numbers', models.JSONField(blank=True, default=list, help_text="List of phone numbers to alert on router offline (e.g. ['0712345678'])")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Notification Settings',
                'verbose_name_plural': 'SMS Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSUnitTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_purchased', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(default='mpesa', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('schema_name', models.SlugField(blank=True, default='', help_text='Tenant schema that initiated this topup', max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Unit Top-up',
                'verbose_name_plural': 'SMS Unit Top-ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSMSWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_units', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('sell_price_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant SMS Wallet',
                'verbose_name_plural': 'Tenant SMS Wallets',
            },
        ),
        migrations.AddField(
            model_name='smsgatewayconfig',
            name='use_inbuilt_system',
            field=models.BooleanField(default=False, help_text="Use the platform's default SMS gateway (Deducts from Tenant Wallet)"),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='event_type',
            field=models.CharField(blank=True, default='', help_text='Automation event this template is linked to', max_length=50),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Platform default template — still editable by tenant'),
        ),
        migrations.AlterField(
            model_name='smsgatewayconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smsgatewayconfig',
            name='provider',
            field=models.CharField(choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('vonage', 'Vonage (Nexmo)'), ('infobip', 'Infobip'), ('beem', 'Beem Africa'), ('advanta', 'Advanta SMS'), ('hubtel', 'Hubtel'), ('bytewave', 'Bytewave'), ('blessedtexts', 'BlessedTexts')], max_length=30),
        ),
        migrations.CreateModel(
            name='SMSCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('topup', 'Topup'), ('debit', 'Debit'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('units', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sms_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.smsmessage')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='messaging.tenantsmswallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
