# Generated by Django 5.2.10 on 2026-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_smsnotificationsettings_smsunittopup_tenantsmswallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='pppoe_expiry_days_before',
        ),
        migrations.AddField(
            model_name='smsnotificationsettings',
            name='pppoe_expiry_intervals',
            field=models.JSONField(blank=True, default=list, help_text='List of {"value": 4, "unit": "days"} objects, e.g. [{"value":4,"unit":"days"},{"value":5,"unit":"hours"}]'),
        ),
    ]
