# Generated by Django 4.2.7 on 2026-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_smsnotificationsettings_pppoe_expiry_days_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDeduplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS Deduplication Log',
                'verbose_name_plural': 'SMS Deduplication Logs',
            },
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='pppoe_new_subscription',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='pppoe_plan_changed',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='pppoe_renewal_confirmation',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='pppoe_service_resumed',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='pppoe_service_suspended',
        ),
        migrations.AddField(
            model_name='smsnotificationsettings',
            name='pppoe_expiry_notification',
            field=models.BooleanField(default=False, help_text='Notify customer once when their subscription has expired'),
        ),
        migrations.AlterField(
            model_name='smsnotificationsettings',
            name='pppoe_payment_confirmation',
            field=models.BooleanField(default=False, help_text='SMS confirmation after a PPPoE payment / renewal is received'),
        ),
    ]
