# Generated by Django 4.2.7 on 2026-06-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_smsdeduplicationlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='hotspot_expiry_minutes_before',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='hotspot_new_subscription',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='hotspot_payment_failed',
        ),
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='hotspot_session_expiry',
        ),
    ]
