# Generated by Django 4.2.7 on 2026-07-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_smsnotificationsettings_hotspot_expiry_minutes_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsgatewayconfig',
            name='provider',
            field=models.CharField(choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('vonage', 'Vonage (Nexmo)'), ('infobip', 'Infobip'), ('beem', 'Beem Africa'), ('advanta', 'Advanta SMS'), ('hubtel', 'Hubtel'), ('bytewave', 'Bytewave'), ('blessedtexts', 'BlessedTexts'), ('texin', 'Texin')], max_length=30),
        ),
    ]