# Generated by Django 4.2.7 on 2026-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_smsgatewayconfig_provider_talksasa'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('event_type', ''), _negated=True)), fields=('event_type',), name='unique_active_event_type_per_tenant'),
        ),
    ]