# Generated by Django 4.2.7 on 2026-10-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_smsunittopup_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotificationsettings',
            name='hotspot_session_expired',
        ),
    ]