# Generated by Django 4.2.7 on 2025-12-31 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherusage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='billing.voucher'),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_voucher_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='core.company'),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='billing.voucherbatch'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_vouchers', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.company'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='plan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.company'),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.company'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billingcycle'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.serviceconnection'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='core.company'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['voucher', 'customer'], name='billing_vou_voucher_524e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['created_at'], name='billing_vou_created_8ddf05_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['batch_number'], name='billing_vou_batch_n_df7e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['status'], name='billing_vou_status_9a7dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['valid_from', 'valid_to'], name='billing_vou_valid_f_c498e9_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='billing_vou_code_4b196f_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['batch', 'status'], name='billing_vou_batch_i_4224e2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_from', 'valid_to'], name='billing_vou_valid_f_d8d16b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['sold_to'], name='billing_vou_sold_to_f40b33_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='billing_rec_receipt_47a6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['customer', 'receipt_date'], name='billing_rec_custome_f2fd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment'], name='billing_rec_payment_168675_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['code'], name='billing_pla_code_927eff_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_type'], name='billing_pla_plan_ty_609bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active'], name='billing_pla_is_acti_0aba70_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['code'], name='billing_pay_code_592d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['method_type'], name='billing_pay_method__23e276_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_active'], name='billing_pay_is_acti_01bfde_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='billing_pay_payment_0825d6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'status'], name='billing_pay_custome_d306bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='billing_pay_payment_bed741_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='billing_pay_transac_904624_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_receipt'], name='billing_pay_mpesa_r_41afc7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='billing_inv_custome_775ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_date'], name='billing_inv_billing_4ccf96_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='billing_inv_due_dat_e51895_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'is_overdue'], name='billing_inv_status_c59426_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['cycle_code'], name='billing_bil_cycle_c_54a792_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['status'], name='billing_bil_status_33ef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['start_date', 'end_date'], name='billing_bil_start_d_3ff550_idx'),
        ),
    ]
