# Generated by Django 4.2.7 on 2026-03-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., '1 Hour', 'Daily Pass'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('validity_type', models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('UNLIMITED', 'Unlimited')], default='HOURS', help_text='Validity period type', max_length=20)),
                ('validity_value', models.PositiveIntegerField(default=1, help_text='Number of minutes/hours/days based on validity_type')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Access duration in minutes (e.g., 60 for 1 hour)')),
                ('limitation_type', models.CharField(choices=[('UNLIMITED', 'Unlimited'), ('DATA', 'Data Plan')], default='UNLIMITED', help_text='Whether plan has data limits', max_length=20)),
                ('data_limit_value', models.PositiveIntegerField(blank=True, help_text='Data limit value', null=True)),
                ('data_limit_unit', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB')], default='MB', help_text='Data limit unit (MB or GB)', max_length=5)),
                ('data_limit_mb', models.PositiveIntegerField(blank=True, help_text='Data limit in MB. Null = unlimited', null=True)),
                ('download_speed', models.PositiveIntegerField(default=5, help_text='Download speed value')),
                ('upload_speed', models.PositiveIntegerField(default=5, help_text='Upload speed value')),
                ('speed_unit', models.CharField(choices=[('MBPS', 'Mbps'), ('KBPS', 'Kbps')], default='MBPS', help_text='Speed unit (Mbps or Kbps)', max_length=10)),
                ('speed_limit_mbps', models.CharField(choices=[('1', '1 Mbps'), ('2', '2 Mbps'), ('5', '5 Mbps'), ('10', '10 Mbps'), ('15', '15 Mbps'), ('20', '20 Mbps'), ('50', '50 Mbps'), ('100', '100 Mbps')], default='5', help_text='Speed limit in Mbps', max_length=10)),
                ('simultaneous_devices', models.PositiveIntegerField(default=1, help_text='Number of devices that can use this plan simultaneously')),
                ('valid_monday', models.BooleanField(default=True)),
                ('valid_tuesday', models.BooleanField(default=True)),
                ('valid_wednesday', models.BooleanField(default=True)),
                ('valid_thursday', models.BooleanField(default=True)),
                ('valid_friday', models.BooleanField(default=True)),
                ('valid_saturday', models.BooleanField(default=True)),
                ('valid_sunday', models.BooleanField(default=True)),
                ('mikrotik_profile', models.CharField(blank=True, help_text='MikroTik hotspot user profile name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotspot_plans', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_plans', to='network.router')),
                ('routers', models.ManyToManyField(blank=True, help_text='Additional routers where this plan is available', related_name='available_hotspot_plans', to='network.router')),
            ],
            options={
                'verbose_name': 'Hotspot Plan',
                'verbose_name_plural': 'Hotspot Plans',
                'ordering': ['router', 'sort_order', 'price'],
                'unique_together': {('router', 'name')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_download',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_enabled',
            field=models.BooleanField(default=False, help_text='Enable burst speed'),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_upload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='ip_pool',
            field=models.ForeignKey(blank=True, help_text='Default IP pool for customers on this plan (Framed-Pool)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='network.ippool'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='priority',
            field=models.IntegerField(default=8, help_text='Queue priority (1=highest bandwidth priority, 8=lowest)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='session_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='speed_unit',
            field=models.CharField(choices=[('MBPS', 'Mbps'), ('KBPS', 'Kbps')], default='MBPS', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_months',
            field=models.IntegerField(blank=True, help_text='Duration in months (for MONTHS validity type)', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_type',
            field=models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours'), ('MINUTES', 'Minutes'), ('MONTHS', 'Months'), ('UNLIMITED', 'Unlimited')], default='DAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='plan',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.CreateModel(
            name='HotspotBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False, help_text='Default branding for all routers without specific branding')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotspot/logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hotspot/backgrounds/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('text_color', models.CharField(default='#1F2937', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('welcome_title', models.CharField(default='Welcome to WiFi', max_length=200)),
                ('welcome_message', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_branding', to='network.router')),
            ],
            options={
                'verbose_name': 'Hotspot Branding',
                'verbose_name_plural': 'Hotspot Branding',
            },
        ),
        migrations.CreateModel(
            name='HotspotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique session ID like HS_1234567890_ABCD', max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('mac_address', models.CharField(help_text='Device MAC address (AA:BB:CC:DD:EE:FF)', max_length=17)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payhero_checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('access_code', models.CharField(blank=True, help_text='WiFi access code (e.g., WIFI-1234)', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Activating'), ('active', 'Active'), ('expired', 'Expired'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('data_used_mb', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='billing.hotspotplan')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_sessions', to='network.router')),
            ],
            options={
                'verbose_name': 'Hotspot Session',
                'verbose_name_plural': 'Hotspot Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='billing_hot_session_63dd93_idx'), models.Index(fields=['payhero_checkout_id'], name='billing_hot_payhero_fc691c_idx'), models.Index(fields=['phone_number'], name='billing_hot_phone_n_3dd94e_idx'), models.Index(fields=['mac_address'], name='billing_hot_mac_add_b2d7bf_idx'), models.Index(fields=['status'], name='billing_hot_status_e2c06e_idx')],
            },
        ),
    ]
