# Generated by Django 4.2.7 on 2026-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payhero_external_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_callback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='channel_id',
            field=models.IntegerField(blank=True, help_text='PayHero channel ID', null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='custom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default payment method for this company'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_payhero_enabled',
            field=models.BooleanField(default=False, help_text='Route payments via PayHero'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paybill_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='till_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('MPESA_STK', 'M-Pesa STK Push'), ('MPESA_TILL', 'M-Pesa Till'), ('MPESA_PAYBILL', 'M-Pesa Paybill'), ('BANK_TRANSFER', 'Bank Transfer'), ('PAYMENT_LINK', 'Payment Link'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('MOBILE_MONEY', 'Mobile Money'), ('VOUCHER', 'Voucher'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payhero_external_reference'], name='billing_pay_payhero_20095b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['channel_id'], name='billing_pay_channel_2c4c32_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_default'], name='billing_pay_is_defa_efb9e1_idx'),
        ),
    ]
