# Generated by Django 5.2.10 on 2026-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_hotspotbranding_hotspotplan_hotspotsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='plan',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
    ]
