# Generated by Django 4.2.7 on 2026-03-17 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_hotspotplan_plan_burst_download_plan_burst_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_name', models.SlugField(default='default_schema', editable=False, max_length=63)),
                ('business_shortcode', models.CharField(help_text='The Paybill/Till Number (e.g., 123456)', max_length=20)),
                ('shortcode_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till Number')], default='PAYBILL', help_text='Type of shortcode (Paybill or Till)', max_length=10)),
                ('passkey', models.CharField(blank=True, help_text='Lipa Na M-Pesa Online Passkey (for STK Push)', max_length=255, null=True)),
                ('consumer_key', models.CharField(help_text='Daraja App Consumer Key', max_length=255)),
                ('consumer_secret', models.CharField(help_text='Daraja App Consumer Secret', max_length=255)),
                ('callback_url', models.URLField(blank=True, help_text='Override default callback URL (optional)', max_length=500, null=True)),
                ('timeout_url', models.URLField(blank=True, help_text='Override default timeout URL (optional)', max_length=500, null=True)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Use Daraja Sandbox environment')),
                ('is_active', models.BooleanField(default=False, help_text='Enable/Disable M-Pesa for this tenant')),
                ('is_default', models.BooleanField(default=False, help_text='Default configuration for this tenant (used when multiple exist)')),
                ('test_mode', models.BooleanField(default=False, help_text='In test mode, transactions are simulated without real money')),
                ('last_validated_at', models.DateTimeField(blank=True, help_text='When the credentials were last successfully validated', null=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of last credential validation', max_length=20)),
                ('validation_error', models.TextField(blank=True, help_text='Error message from last validation')),
                ('daily_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total transaction amount per day', max_digits=12, null=True)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum allowed transaction amount', max_digits=10)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=150000.0, help_text='Maximum allowed transaction amount (Safaricom limit is 150K)', max_digits=10)),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(editable=False, max_length=63)),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business'), ('QUERY', 'Transaction Query'), ('REVERSAL', 'Transaction Reversal')], default='STK_PUSH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('account_reference', models.CharField(blank=True, max_length=50)),
                ('transaction_desc', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='payment',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AddIndex(
            model_name='invoiceitempayment',
            index=models.Index(fields=['schema_name', 'method_type'], name='billing_inv_schema__4ed090_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['schema_name', 'status', 'payment_date'], name='billing_pay_schema__358d42_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['schema_name', 'receipt_date'], name='billing_rec_schema__9aa460_idx'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.mpesaconfiguration'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_log', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitempayment',
            name='mpesa_configuration',
            field=models.ForeignKey(blank=True, help_text='Link to tenant-specific M-Pesa configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='billing.mpesaconfiguration'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='billing.mpesatransaction'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['merchant_request_id'], name='billing_mpe_merchan_70f984_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='billing_mpe_checkou_404fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_id'], name='billing_mpe_transac_7ce985_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', 'created_at'], name='billing_mpe_status_6af1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['schema_name', 'status'], name='billing_mpe_schema__4adb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['schema_name', 'is_active'], name='billing_mpe_schema__6e1fef_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['schema_name', 'is_default'], name='billing_mpe_schema__c30245_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['business_shortcode', 'shortcode_type'], name='billing_mpe_busines_76f87a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mpesaconfiguration',
            unique_together={('schema_name', 'business_shortcode', 'shortcode_type')},
        ),
    ]
