# Generated by Django 4.2.7 on 2026-01-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_payhero_external_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='burst_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='contract_period',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='early_termination_fee',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='prorated_billing',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tax_inclusive',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='fup_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fup_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='data_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='download_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('INTERNET', 'Internet'), ('ADDON', 'Add-on'), ('BUNDLE', 'Bundle'), ('TOPUP', 'Top-up'), ('PPPOE', 'PPPoE'), ('HOTSPOT', 'Hotspot'), ('STATIC', 'Static IP')], default='PPPOE', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='upload_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_public'], name='billing_pla_is_publ_35f18d_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_popular'], name='billing_pla_is_popu_3868c4_idx'),
        ),
    ]
