# Generated by Django 5.2.10 on 2026-02-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billingcycle_schema_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='burst_download',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='burst_upload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='session_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='speed_unit',
            field=models.CharField(choices=[('MBPS', 'Mbps'), ('KBPS', 'Kbps')], default='MBPS', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_type',
            field=models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours'), ('MINUTES', 'Minutes'), ('UNLIMITED', 'Unlimited')], default='DAYS', max_length=20),
        ),
    ]
