# Generated by Django 4.2.7 on 2026-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_mpesaconfiguration_mpesatransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa Receipt Number (unique)', max_length=50, unique=True),
        ),
    ]
