# Generated by Django 4.2.7 on 2026-03-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_mpesatransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaconfiguration',
            name='schema_name',
            field=models.SlugField(editable=False, max_length=63),
        ),
    ]
