# Generated by Django 5.2.10 on 2026-02-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_plan_time_and_session_fields'),
        ('network', '0004_remove_hotspotuser_network_hot_last_se_292ec0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotplan',
            name='data_limit_unit',
            field=models.CharField(choices=[('MB', 'MB'), ('GB', 'GB')], default='MB', help_text='Data limit unit (MB or GB)', max_length=5),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='data_limit_value',
            field=models.PositiveIntegerField(blank=True, help_text='Data limit value', null=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='download_speed',
            field=models.PositiveIntegerField(default=5, help_text='Download speed value'),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='limitation_type',
            field=models.CharField(choices=[('UNLIMITED', 'Unlimited'), ('DATA', 'Data Plan')], default='UNLIMITED', help_text='Whether plan has data limits', max_length=20),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='routers',
            field=models.ManyToManyField(blank=True, help_text='Additional routers where this plan is available', related_name='available_hotspot_plans', to='network.router'),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='simultaneous_devices',
            field=models.PositiveIntegerField(default=1, help_text='Number of devices that can use this plan simultaneously'),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='speed_unit',
            field=models.CharField(choices=[('MBPS', 'Mbps'), ('KBPS', 'Kbps')], default='MBPS', help_text='Speed unit (Mbps or Kbps)', max_length=10),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='upload_speed',
            field=models.PositiveIntegerField(default=5, help_text='Upload speed value'),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='valid_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='validity_type',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('UNLIMITED', 'Unlimited')], default='HOURS', help_text='Validity period type', max_length=20),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='validity_value',
            field=models.PositiveIntegerField(default=1, help_text='Number of minutes/hours/days based on validity_type'),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Access duration in minutes (e.g., 60 for 1 hour)'),
        ),
    ]
