# Generated by Django 4.2.7 on 2026-03-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_mpesaconfiguration_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotsession',
            name='is_roaming',
            field=models.BooleanField(default=False, help_text='True if purchased at a different router than their last session'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='roamed_from',
            field=models.CharField(blank=True, help_text='The name of the previous router they connected to', max_length=100, null=True),
        ),
    ]
