# Generated by Django 5.2.10 on 2026-02-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_hotspot_plan_enhanced_fields'),
        ('network', '0007_ipam_router_fk_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='burst_enabled',
            field=models.BooleanField(default=False, help_text='Enable burst speed'),
        ),
        migrations.AddField(
            model_name='plan',
            name='ip_pool',
            field=models.ForeignKey(blank=True, help_text='Default IP pool for customers on this plan (Framed-Pool)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='network.ippool'),
        ),
        migrations.AddField(
            model_name='plan',
            name='priority',
            field=models.IntegerField(default=8, help_text='Queue priority (1=highest bandwidth priority, 8=lowest)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_months',
            field=models.IntegerField(blank=True, help_text='Duration in months (for MONTHS validity type)', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity_type',
            field=models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours'), ('MINUTES', 'Minutes'), ('MONTHS', 'Months'), ('UNLIMITED', 'Unlimited')], default='DAYS', max_length=20),
        ),
    ]
