# Generated by Django 4.2.7 on 2026-03-31 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_routertenantindex_router_id_and_more'),
        ('billing', '0007_hotspotsession_is_roaming_hotspotsession_roamed_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTumaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=63, unique=True)),
                ('tuma_business_id', models.CharField(blank=True, max_length=64)),
                ('tuma_business_email', models.EmailField(blank=True, max_length=254)),
                ('tuma_business_api_key', models.CharField(blank=True, max_length=255)),
                ('active_mode', models.CharField(blank=True, choices=[('TILL', 'Till'), ('BANK', 'Bank')], max_length=10)),
                ('collection_reference_id', models.CharField(blank=True, db_index=True, help_text='Tuma reference ID for the selected bank/till/paybill', max_length=64)),
                ('collection_reference_code', models.CharField(blank=True, help_text='Reference code (e.g., BUYGOODS, PAYBILL, EQUITY, TILL_NUMBER)', max_length=30)),
                ('collection_reference_name', models.CharField(blank=True, help_text='Display name of the selected bank or payment method', max_length=120)),
                ('collection_account_number', models.CharField(blank=True, help_text='Account number (till number, paybill number, or bank account)', max_length=50)),
                ('till_number', models.CharField(blank=True, max_length=30)),
                ('bank_id', models.CharField(blank=True, max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tuma Configuration',
                'verbose_name_plural': 'Tuma Configurations',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_callback_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_merchant_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_result_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tuma_merchant_request_id'], name='billing_pay_tuma_me_1d50f0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tuma_checkout_request_id'], name='billing_pay_tuma_ch_7e5b70_idx'),
        ),
        migrations.AddField(
            model_name='tenanttumaconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuma_configs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceitempayment',
            name='tuma_configuration',
            field=models.ForeignKey(blank=True, help_text='Link to tenant-specific Tuma configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='billing.tenanttumaconfig'),
        ),
        migrations.AddIndex(
            model_name='tenanttumaconfig',
            index=models.Index(fields=['schema_name', 'is_active'], name='billing_ten_schema__ffceed_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttumaconfig',
            index=models.Index(fields=['collection_reference_id'], name='billing_ten_collect_97bbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttumaconfig',
            index=models.Index(fields=['collection_reference_code'], name='billing_ten_collect_44d74a_idx'),
        ),
    ]
