# Generated by Django 5.2.10 on 2026-04-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_plan_priority_ippool_months_burst'),
        ('core', '0003_changelog_tumacallbackmap_featurerequest_and_more'),
        ('customers', '0002_make_id_number_optional'),
        ('network', '0012_alter_ipaddress_ip_pool_alter_router_api_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(editable=False, max_length=63)),
                ('canonical_phone', models.CharField(blank=True, db_index=True, help_text='Primary phone number for this client (stable across devices)', max_length=15, null=True)),
                ('canonical_username', models.CharField(blank=True, db_index=True, help_text='Permanent RADIUS username for this hotspot client (e.g. MXA-BKCS). Auto-generated on first purchase. Reused across all sessions on any device.', max_length=20, null=True, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('external_client_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hotspot Client',
                'verbose_name_plural': 'Hotspot Clients',
            },
        ),
        migrations.CreateModel(
            name='HotspotClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, help_text='Device MAC address (may change due to randomization)', max_length=17)),
                ('device_token', models.CharField(blank=True, db_index=True, help_text='Push notification token for this device', max_length=128, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotspot Client Device',
                'verbose_name_plural': 'Hotspot Client Devices',
            },
        ),
        migrations.CreateModel(
            name='MpesaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_name', models.SlugField(editable=False, max_length=63)),
                ('business_shortcode', models.CharField(help_text='The Paybill/Till Number (e.g., 123456)', max_length=20)),
                ('shortcode_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till Number')], default='PAYBILL', help_text='Type of shortcode (Paybill or Till)', max_length=10)),
                ('passkey', models.CharField(blank=True, help_text='Lipa Na M-Pesa Online Passkey (for STK Push)', max_length=255, null=True)),
                ('consumer_key', models.CharField(help_text='Daraja App Consumer Key', max_length=255)),
                ('consumer_secret', models.CharField(help_text='Daraja App Consumer Secret', max_length=255)),
                ('callback_url', models.URLField(blank=True, help_text='Override default callback URL (optional)', max_length=500, null=True)),
                ('timeout_url', models.URLField(blank=True, help_text='Override default timeout URL (optional)', max_length=500, null=True)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Use Daraja Sandbox environment')),
                ('is_active', models.BooleanField(default=False, help_text='Enable/Disable M-Pesa for this tenant')),
                ('is_default', models.BooleanField(default=False, help_text='Default configuration for this tenant (used when multiple exist)')),
                ('test_mode', models.BooleanField(default=False, help_text='In test mode, transactions are simulated without real money')),
                ('last_validated_at', models.DateTimeField(blank=True, help_text='When the credentials were last successfully validated', null=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of last credential validation', max_length=20)),
                ('validation_error', models.TextField(blank=True, help_text='Error message from last validation')),
                ('daily_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total transaction amount per day', max_digits=12, null=True)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum allowed transaction amount', max_digits=10)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=150000.0, help_text='Maximum allowed transaction amount (Safaricom limit is 150K)', max_digits=10)),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(editable=False, max_length=63)),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='M-Pesa Receipt Number (unique)', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business'), ('QUERY', 'Transaction Query'), ('REVERSAL', 'Transaction Reversal')], default='STK_PUSH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('account_reference', models.CharField(blank=True, max_length=50)),
                ('transaction_desc', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StkCancellationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=63)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('consecutive_1032_count', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_code', models.IntegerField(blank=True, null=True)),
                ('last_checkout_request_id', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STK Cancellation Tracker',
                'verbose_name_plural': 'STK Cancellation Trackers',
            },
        ),
        migrations.CreateModel(
            name='TenantTumaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=63, unique=True)),
                ('tuma_business_id', models.CharField(blank=True, max_length=64)),
                ('tuma_business_email', models.EmailField(blank=True, max_length=254)),
                ('tuma_business_api_key', models.CharField(blank=True, max_length=255)),
                ('active_mode', models.CharField(blank=True, choices=[('TILL', 'Till'), ('BANK', 'Bank')], max_length=10)),
                ('collection_reference_id', models.CharField(blank=True, db_index=True, help_text='Tuma reference ID for the selected bank/till/paybill', max_length=64)),
                ('collection_reference_code', models.CharField(blank=True, help_text='Reference code (e.g., BUYGOODS, PAYBILL, EQUITY, TILL_NUMBER)', max_length=30)),
                ('collection_reference_name', models.CharField(blank=True, help_text='Display name of the selected bank or payment method', max_length=120)),
                ('collection_account_number', models.CharField(blank=True, help_text='Account number (till number, paybill number, or bank account)', max_length=50)),
                ('till_number', models.CharField(blank=True, max_length=30)),
                ('bank_id', models.CharField(blank=True, max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tuma Configuration',
                'verbose_name_plural': 'Tuma Configurations',
            },
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='is_roaming',
            field=models.BooleanField(default=False, help_text='True if purchased at a different router than their last session'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='The payment record associated with this hotspot session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_sessions', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='roamed_from',
            field=models.CharField(blank=True, help_text='The name of the previous router they connected to', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='tuma_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text="Tuma checkout request ID for this session's payment", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='tuma_merchant_request_id',
            field=models.CharField(blank=True, db_index=True, help_text="Tuma merchant request ID for this session's payment", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotspot_session',
            field=models.ForeignKey(blank=True, help_text='Explicit link to the hotspot session that initiated this payment (for STK Push)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.hotspotsession'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_callback_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_merchant_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_result_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuma_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='hotspot_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_batches', to='billing.hotspotplan'),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='is_payhero_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer linked to this payment. Set null if customer is deleted to preserve transaction history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer linked to this receipt. Set null if customer is deleted to preserve receipt history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='voucherbatch',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('schema_name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherbatch',
            unique_together={('schema_name', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['schema_name', 'receipt_date'], name='billing_rec_schema__9aa460_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['schema_name'], name='billing_vou_schema__7709ae_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['hotspot_plan'], name='billing_vou_hotspot_6feddc_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['schema_name'], name='billing_vou_schema__5fd457_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['schema_name'], name='billing_vou_schema__46b37d_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'canonical_phone'], name='billing_hot_schema__4ebe69_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'email'], name='billing_hot_schema__410ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'external_client_id'], name='billing_hot_schema__3cacd7_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'last_seen_at'], name='billing_hot_schema__a1f722_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['canonical_username'], name='billing_hot_canonic_c48ac3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotspotclient',
            unique_together={('schema_name', 'canonical_phone'), ('schema_name', 'email')},
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='hotspot_client',
            field=models.ForeignKey(blank=True, help_text='The client who owns this session (stable across MAC randomization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='billing.hotspotclient'),
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['tuma_merchant_request_id'], name='billing_hot_tuma_me_03b441_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['tuma_checkout_request_id'], name='billing_hot_tuma_ch_ba787f_idx'),
        ),
        migrations.AddField(
            model_name='hotspotclientdevice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='billing.hotspotclient'),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitempayment',
            name='mpesa_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='billing.mpesaconfiguration'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.mpesaconfiguration'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_log', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='billing.mpesatransaction'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tuma_merchant_request_id'], name='billing_pay_tuma_me_1d50f0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tuma_checkout_request_id'], name='billing_pay_tuma_ch_7e5b70_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hotspot_session'], name='billing_pay_hotspot_ff1790_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['schema_name', 'status', 'payment_date'], name='billing_pay_schema__358d42_idx'),
        ),
        migrations.AddIndex(
            model_name='stkcancellationtracker',
            index=models.Index(fields=['schema_name', 'phone_number'], name='billing_stk_schema__78aec8_idx'),
        ),
        migrations.AddIndex(
            model_name='stkcancellationtracker',
            index=models.Index(fields=['schema_name', 'is_blocked'], name='billing_stk_schema__6c111c_idx'),
        ),
        migrations.AddIndex(
            model_name='stkcancellationtracker',
            index=models.Index(fields=['schema_name', 'consecutive_1032_count'], name='billing_stk_schema__5f8080_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stkcancellationtracker',
            unique_together={('schema_name', 'phone_number')},
        ),
        migrations.AddField(
            model_name='tenanttumaconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuma_configs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceitempayment',
            name='tuma_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='billing.tenanttumaconfig'),
        ),
        migrations.AddIndex(
            model_name='invoiceitempayment',
            index=models.Index(fields=['schema_name', 'method_type'], name='billing_inv_schema__4ed090_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclientdevice',
            index=models.Index(fields=['mac_address'], name='billing_hot_mac_add_41b346_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclientdevice',
            index=models.Index(fields=['device_token'], name='billing_hot_device__3b1e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclientdevice',
            index=models.Index(fields=['client', 'last_seen_at'], name='billing_hot_client__aa03c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotspotclientdevice',
            unique_together={('client', 'mac_address')},
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['schema_name', 'is_active'], name='billing_mpe_schema__6e1fef_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['schema_name', 'is_default'], name='billing_mpe_schema__c30245_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['business_shortcode', 'shortcode_type'], name='billing_mpe_busines_76f87a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mpesaconfiguration',
            unique_together={('schema_name', 'business_shortcode', 'shortcode_type')},
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['merchant_request_id'], name='billing_mpe_merchan_70f984_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='billing_mpe_checkou_404fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_id'], name='billing_mpe_transac_7ce985_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', 'created_at'], name='billing_mpe_status_6af1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['schema_name', 'status'], name='billing_mpe_schema__4adb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttumaconfig',
            index=models.Index(fields=['schema_name', 'is_active'], name='billing_ten_schema__ffceed_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttumaconfig',
            index=models.Index(fields=['collection_reference_id'], name='billing_ten_collect_97bbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttumaconfig',
            index=models.Index(fields=['collection_reference_code'], name='billing_ten_collect_44d74a_idx'),
        ),
    ]
