# Generated by Django 4.2.7 on 2026-03-31 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_routertenantindex_router_id_and_more'),
        ('billing', '0008_tenanttumaconfig_payment_tuma_callback_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='is_payhero_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='mpesa_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='billing.mpesaconfiguration'),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='tuma_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='billing.tenanttumaconfig'),
        ),
        migrations.AlterField(
            model_name='tenanttumaconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuma_configs', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='StkCancellationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=63)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('consecutive_1032_count', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_code', models.IntegerField(blank=True, null=True)),
                ('last_checkout_request_id', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STK Cancellation Tracker',
                'verbose_name_plural': 'STK Cancellation Trackers',
                'indexes': [models.Index(fields=['schema_name', 'phone_number'], name='billing_stk_schema__78aec8_idx'), models.Index(fields=['schema_name', 'is_blocked'], name='billing_stk_schema__6c111c_idx'), models.Index(fields=['schema_name', 'consecutive_1032_count'], name='billing_stk_schema__5f8080_idx')],
                'unique_together': {('schema_name', 'phone_number')},
            },
        ),
    ]
