# Generated by Django 5.2.10 on 2026-05-29 23:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_hotspotclient_hotspotclientdevice_mpesaconfiguration_and_more'),
        ('network', '0013_add_router_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(default='default_schema', editable=False, max_length=63)),
                ('name', models.CharField(max_length=200)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='hotspot/ads/')),
                ('media_url', models.URLField(blank=True, help_text='External video URL (YouTube, etc.)')),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image')], default='VIDEO', max_length=10)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('target_url', models.URLField(blank=True, help_text='Where to redirect on click (optional)')),
                ('reward_enabled', models.BooleanField(default=True)),
                ('reward_minutes', models.PositiveIntegerField(default=30, help_text='Minutes of free internet after watching (0–60)')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower = shown first')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('completions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotAdGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(default='default_schema', editable=False, max_length=63)),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('access_code', models.CharField(max_length=20, unique=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='invoiceitempayment',
            name='billing_inv_channel_65c8c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_payhero_20095b_idx',
        ),
        migrations.RemoveField(
            model_name='invoiceitempayment',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='invoiceitempayment',
            name='is_payhero_enabled',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payhero_external_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='raw_callback',
        ),
        migrations.RemoveField(
            model_name='tenanttumaconfig',
            name='tenant',
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='is_global_template',
            field=models.BooleanField(default=False, help_text='If True, this plan is cloned automatically to any new router that gets created'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='radius_username',
            field=models.CharField(blank=True, help_text='RADIUS credential used (may differ from access_code for multi-device clients)', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitempayment',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='account_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa Receipt Number (unique)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_type',
            field=models.CharField(choices=[('STK_PUSH', 'STK Push'), ('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business'), ('QUERY', 'Transaction Query'), ('REVERSAL', 'Transaction Reversal')], default='STK_PUSH', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Set to null if the payment method is deleted to preserve history', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoiceitempayment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tuma_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='hotspotplan',
            index=models.Index(fields=['router', 'is_active', 'sort_order', 'price'], name='hotspot_plan_fast_list_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['radius_username'], name='billing_hot_radius__86bd6c_idx'),
        ),
        migrations.AddField(
            model_name='hotspotad',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotspot_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotspotad',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_ads', to='network.router'),
        ),
        migrations.AddField(
            model_name='hotspotadgrant',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='billing.hotspotad'),
        ),
        migrations.AddField(
            model_name='hotspotadgrant',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.router'),
        ),
        migrations.AddIndex(
            model_name='hotspotad',
            index=models.Index(fields=['schema_name', 'is_active', 'priority'], name='billing_hot_schema__647e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotadgrant',
            index=models.Index(fields=['schema_name', 'mac_address', 'expires_at'], name='billing_hot_schema__8f9b6f_idx'),
        ),
    ]
