# Generated by Django 5.2.10 on 2026-06-10 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_hotspotad_hotspotadgrant_and_more'),
        ('customers', '0004_customer_location_customer_prepaid_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('schema_name', models.SlugField(default='default_schema', editable=False, max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='c2b_urls_registered',
            field=models.BooleanField(default=False, help_text='Whether C2B callback URLs have been registered with Safaricom'),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='c2b_urls_registered_at',
            field=models.DateTimeField(blank=True, help_text='When C2B URLs were last registered', null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.mpesaconfiguration'),
        ),
        migrations.AddIndex(
            model_name='mpesaconfiguration',
            index=models.Index(fields=['c2b_urls_registered'], name='billing_mpe_c2b_url_5bdbe1_idx'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='customers.serviceconnection'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='billing_sub_custome_8375ed_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at', 'status'], name='billing_sub_expires_264958_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['schema_name', 'status'], name='billing_sub_schema__d6c1dc_idx'),
        ),
    ]
