# Generated by Django 4.2.7 on 2026-04-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_invoiceitempayment_channel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(editable=False, max_length=63)),
                ('canonical_phone', models.CharField(blank=True, db_index=True, help_text='Primary phone number for this client (stable across devices)', max_length=15, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('external_client_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hotspot Client',
                'verbose_name_plural': 'Hotspot Clients',
            },
        ),
        migrations.CreateModel(
            name='HotspotClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, help_text='Device MAC address (may change due to randomization)', max_length=17)),
                ('device_token', models.CharField(blank=True, db_index=True, help_text='Push notification token for this device', max_length=128, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotspot Client Device',
                'verbose_name_plural': 'Hotspot Client Devices',
            },
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='The payment record associated with this hotspot session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_sessions', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='tuma_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text="Tuma checkout request ID for this session's payment", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='tuma_merchant_request_id',
            field=models.CharField(blank=True, db_index=True, help_text="Tuma merchant request ID for this session's payment", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotspot_session',
            field=models.ForeignKey(blank=True, help_text='Explicit link to the hotspot session that initiated this payment (for STK Push)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.hotspotsession'),
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['tuma_merchant_request_id'], name='billing_hot_tuma_me_03b441_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['tuma_checkout_request_id'], name='billing_hot_tuma_ch_ba787f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hotspot_session'], name='billing_pay_hotspot_ff1790_idx'),
        ),
        migrations.AddField(
            model_name='hotspotclientdevice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='billing.hotspotclient'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'canonical_phone'], name='billing_hot_schema__4ebe69_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'email'], name='billing_hot_schema__410ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'external_client_id'], name='billing_hot_schema__3cacd7_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['schema_name', 'last_seen_at'], name='billing_hot_schema__a1f722_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotspotclient',
            unique_together={('schema_name', 'canonical_phone'), ('schema_name', 'email')},
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='hotspot_client',
            field=models.ForeignKey(blank=True, help_text='The client who owns this session (stable across MAC randomization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='billing.hotspotclient'),
        ),
        migrations.AddIndex(
            model_name='hotspotclientdevice',
            index=models.Index(fields=['mac_address'], name='billing_hot_mac_add_41b346_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclientdevice',
            index=models.Index(fields=['device_token'], name='billing_hot_device__3b1e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotclientdevice',
            index=models.Index(fields=['client', 'last_seen_at'], name='billing_hot_client__aa03c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotspotclientdevice',
            unique_together={('client', 'mac_address')},
        ),
    ]
