# Generated by Django 4.2.7 on 2026-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_subscription_mpesaconfiguration_c2b_urls_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=63, unique=True)),
                ('auto_generate_enabled', models.BooleanField(default=False, help_text='When enabled, automatically generates invoices for PPPoE subscribers')),
                ('days_before_expiry', models.IntegerField(default=5, help_text='Generate invoice N days before subscription expires')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Setting',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
    ]
