# Generated by Django 4.2.7 on 2026-04-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_hotspotclient_hotspotclientdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherbatch',
            name='hotspot_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_batches', to='billing.hotspotplan'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['hotspot_plan'], name='billing_vou_hotspot_6feddc_idx'),
        ),
    ]
