# Generated by Django 4.2.7 on 2026-04-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_voucherbatch_hotspot_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='voucherbatch',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='schema_name',
            field=models.SlugField(default='default_schema', editable=False, max_length=63),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('schema_name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherbatch',
            unique_together={('schema_name', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['schema_name'], name='billing_vou_schema__7709ae_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherbatch',
            index=models.Index(fields=['schema_name'], name='billing_vou_schema__5fd457_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['schema_name'], name='billing_vou_schema__46b37d_idx'),
        ),
    ]
