# Generated by Django 4.2.7 on 2026-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoicesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='speed_unit',
            field=models.CharField(choices=[('MBPS', 'Mbps'), ('KBPS', 'Kbps'), ('GBPS', 'Gbps')], default='MBPS', max_length=10),
        ),
    ]
