# Generated by Django 4.2.7 on 2026-07-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_router_hide_plan_speed'),
        ('billing', '0012_alter_plan_speed_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotPruneSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=63, unique=True)),
                ('prune_window_days', models.PositiveIntegerField(choices=[(1, '1 Day'), (7, '7 Days'), (30, '30 Days')], default=30, help_text='Hotspot clients whose most recent session expired more than this many days ago will be automatically deleted.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_pruned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotspot Prune Setting',
                'verbose_name_plural': 'Hotspot Prune Settings',
            },
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='is_free_trial',
            field=models.BooleanField(default=False, help_text='If True, this plan is free — no payment required. One claim per device (MAC) ever.'),
        ),
        migrations.CreateModel(
            name='HotspotFreeTrialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('access_code', models.CharField(blank=True, max_length=25)),
                ('router', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.router')),
            ],
            options={
                'verbose_name': 'Free Trial Usage',
                'verbose_name_plural': 'Free Trial Usages',
            },
        ),
    ]