# Generated by Django 4.2.7 on 2026-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_hotspotprunesettings_hotspotplan_is_free_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotclient',
            name='canonical_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Primary phone number for this client (stable across devices)', max_length=20, null=True),
        ),
    ]