# Generated by Django 4.2.7 on 2026-04-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_serviceconnection_billing_account_number_and_more'),
        ('billing', '0013_alter_payment_customer_alter_receipt_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer linked to this payment. Set null if customer is deleted to preserve transaction history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer linked to this receipt. Set null if customer is deleted to preserve receipt history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='customers.customer'),
        ),
    ]
