# Generated by Django 4.2.7 on 2026-04-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_payment_customer_alter_receipt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotclient',
            name='canonical_username',
            field=models.CharField(blank=True, db_index=True, help_text='Permanent RADIUS username for this hotspot client (e.g. MXA-BKCS). Auto-generated on first purchase. Reused across all sessions on any device.', max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='hotspotclient',
            index=models.Index(fields=['canonical_username'], name='billing_hot_canonic_c48ac3_idx'),
        ),
    ]
