# Generated by Django 4.2.7 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_hotspotclient_hotspotclientdevice_mpesaconfiguration_and_more'),
        ('billing', '0015_hotspotclient_canonical_username_and_more'),
    ]

    operations = [
    ]
