# Generated by Django 4.2.7 on 2026-07-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_currency_default_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotplan',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
    ]