# Generated by Django 4.2.7 on 2026-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_hotspotplan_currency_alter_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('HOTSPOT', 'Hotspot'), ('PPPOE', 'PPPoE'), ('OTHER', 'Other')], db_index=True, help_text='Set once at creation; survives hotspot_session deletion via pruning', max_length=10),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['service_type'], name='billing_pay_service_6000c2_idx'),
        ),
    ]