# Generated by Django 4.2.7 on 2026-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_payment_service_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['schema_name', 'status', '-payment_date', 'service_type'], name='pay_ticker_idx'),
        ),
    ]