# Generated by Django 4.2.7 on 2026-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_payment_pay_ticker_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspotbranding',
            options={'verbose_name': 'Hotspot Branding', 'verbose_name_plural': 'Hotspot Brandings'},
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='is_tv_plan',
            field=models.BooleanField(default=False, help_text="If True, this plan only appears under 'Pay for TV' in the captive portal (Smart TV / limited-browser devices)."),
        ),
        migrations.AddIndex(
            model_name='hotspotplan',
            index=models.Index(fields=['router', 'is_active', 'is_tv_plan'], name='hotspot_plan_tv_idx'),
        ),
    ]