# Generated by Django 4.2.7 on 2026-09-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_hotspotbranding_options_hotspotplan_is_tv_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='validity_type',
            field=models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours'), ('MINUTES', 'Minutes'), ('MONTHS', 'Months'), ('CALENDAR_MONTH', 'Same Day Monthly'), ('UNLIMITED', 'Unlimited')], default='DAYS', max_length=20),
        ),
    ]