# Generated by Django 4.2.7 on 2026-09-17 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_accesspoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0020_alter_plan_validity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending Reply'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('subject', models.CharField(blank=True, default='Hotspot Support', max_length=200)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=260)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unread_by_admin', models.BooleanField(default=True)),
                ('unread_by_customer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hotspot_chats', to=settings.AUTH_USER_MODEL)),
                ('hotspot_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='billing.hotspotclient')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_chat_threads', to='network.router')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('sender_name', models.CharField(blank=True, default='', max_length=160)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='billing.hotspotchatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotspotchatthread',
            index=models.Index(fields=['status', 'last_message_at'], name='billing_hot_status_38e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotchatthread',
            index=models.Index(fields=['unread_by_admin', 'status'], name='billing_hot_unread__be1b76_idx'),
        ),
    ]