# Generated by Django 4.2.7 on 2026-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_hotspotchatthread_hotspotchatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotsession',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, help_text='WiFi access code (e.g., WIFI-1234)', max_length=20, null=True),
        ),
    ]