# Generated by Django 4.2.7 on 2026-07-13 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMapElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('element_type', models.CharField(choices=[('CABLE', 'Fiber Cable'), ('SPLITTER', 'Splitter'), ('ODF', 'ODF / Distribution Frame'), ('NAP', 'Network Access Point'), ('POLE', 'Pole'), ('MANHOLE', 'Manhole / Handhole'), ('JOINT_CLOSURE', 'Joint Closure'), ('CUSTOMER_DROP', 'Customer Drop'), ('EQUIPMENT', 'Router / Equipment'), ('ISSUE', 'Fault / Cut'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('geometry_type', models.CharField(choices=[('POINT', 'Point'), ('LINE', 'Line')], default='POINT', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PLANNED', 'Planned'), ('FAULTY', 'Faulty'), ('DECOMMISSIONED', 'Decommissioned')], db_index=True, default='ACTIVE', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('', '—'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='', max_length=10)),
                ('coordinates', models.JSONField(default=list)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('linked_router_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_map_elements', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fiber_map.networkmapelement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_map_elements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['element_type', 'status'], name='fiber_map_n_element_997d3b_idx')],
            },
        ),
    ]