# Generated by Django 4.2.7 on 2026-03-22 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_serviceconnection_billing_account_number_and_more'),
        ('billing', '0007_plan_priority_ippool_months_burst'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FUPPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('data_limit_gb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('throttle_download_mbps', models.PositiveIntegerField()),
                ('throttle_upload_mbps', models.PositiveIntegerField(default=1)),
                ('reset_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SUBSCRIPTION', 'Subscription')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('auto_enforce', models.BooleanField(default=True)),
                ('notify_on_violation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fup_policies', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fup_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FUP Policy',
                'verbose_name_plural': 'FUP Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FUPUsageWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('limit_bytes', models.BigIntegerField()),
                ('usage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('VIOLATED', 'Violated'), ('THROTTLED', 'Throttled'), ('RESET', 'Reset')], default='NORMAL', max_length=20)),
                ('first_exceeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_accounting_update_at', models.DateTimeField(blank=True, null=True)),
                ('is_throttled', models.BooleanField(default=False)),
                ('throttled_at', models.DateTimeField(blank=True, null=True)),
                ('unthrottled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_usage_windows', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fup_usage_windows', to='billing.plan')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_windows', to='fup.fuppolicy')),
                ('service_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_usage_windows', to='customers.serviceconnection')),
            ],
            options={
                'verbose_name': 'FUP Usage Window',
                'verbose_name_plural': 'FUP Usage Windows',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='FUPThrottleState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_download_mbps', models.PositiveIntegerField()),
                ('original_upload_mbps', models.PositiveIntegerField()),
                ('throttled_download_mbps', models.PositiveIntegerField()),
                ('throttled_upload_mbps', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_throttle_states', to='customers.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throttle_states', to='fup.fuppolicy')),
                ('service_connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fup_throttle_state', to='customers.serviceconnection')),
            ],
            options={
                'verbose_name': 'FUP Throttle State',
                'verbose_name_plural': 'FUP Throttle States',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='FUPPolicyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_plan_links', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_policy_links', to='billing.plan')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='fup.fuppolicy')),
            ],
            options={
                'verbose_name': 'FUP Policy Plan Link',
                'verbose_name_plural': 'FUP Policy Plan Links',
            },
        ),
        migrations.CreateModel(
            name='FUPAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('PLAN_LINKED', 'Plan Linked'), ('PLAN_UNLINKED', 'Plan Unlinked'), ('USER_THROTTLED', 'User Throttled'), ('USER_RELEASED', 'User Released'), ('WINDOW_RESET', 'Window Reset')], max_length=40)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_audit_logs', to='customers.customer')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='fup.fuppolicy')),
                ('service_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_audit_logs', to='customers.serviceconnection')),
            ],
            options={
                'verbose_name': 'FUP Audit Log',
                'verbose_name_plural': 'FUP Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FUPViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_usage_bytes', models.BigIntegerField()),
                ('limit_bytes', models.BigIntegerField()),
                ('exceeded_by_bytes', models.BigIntegerField()),
                ('action_taken', models.CharField(choices=[('WARNED', 'Warned'), ('THROTTLED', 'Throttled'), ('RETHROTTLED', 'Re-throttled'), ('RELEASED', 'Released'), ('RESET', 'Reset')], max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_violations', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fup_violations', to='billing.plan')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='fup.fuppolicy')),
                ('service_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_violations', to='customers.serviceconnection')),
                ('usage_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='fup.fupusagewindow')),
            ],
            options={
                'verbose_name': 'FUP Violation',
                'verbose_name_plural': 'FUP Violations',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['status'], name='fup_fupviol_status_aa5e4d_idx'), models.Index(fields=['occurred_at'], name='fup_fupviol_occurre_1dc806_idx'), models.Index(fields=['action_taken'], name='fup_fupviol_action__a59322_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fupusagewindow',
            index=models.Index(fields=['status'], name='fup_fupusag_status_ed51b4_idx'),
        ),
        migrations.AddIndex(
            model_name='fupusagewindow',
            index=models.Index(fields=['is_throttled'], name='fup_fupusag_is_thro_b87e63_idx'),
        ),
        migrations.AddIndex(
            model_name='fupusagewindow',
            index=models.Index(fields=['period_start', 'period_end'], name='fup_fupusag_period__cbb077_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fupusagewindow',
            unique_together={('policy', 'service_connection', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='fupthrottlestate',
            index=models.Index(fields=['active'], name='fup_fupthro_active_b27e73_idx'),
        ),
        migrations.AddIndex(
            model_name='fupthrottlestate',
            index=models.Index(fields=['applied_at'], name='fup_fupthro_applied_026a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuppolicyplan',
            index=models.Index(fields=['is_active'], name='fup_fuppoli_is_acti_887fb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fuppolicyplan',
            unique_together={('policy', 'plan')},
        ),
        migrations.AddIndex(
            model_name='fuppolicy',
            index=models.Index(fields=['status'], name='fup_fuppoli_status_d96219_idx'),
        ),
        migrations.AddIndex(
            model_name='fuppolicy',
            index=models.Index(fields=['is_active'], name='fup_fuppoli_is_acti_dd1dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='fuppolicy',
            index=models.Index(fields=['reset_period'], name='fup_fuppoli_reset_p_2de1ef_idx'),
        ),
    ]
