# Generated by Django 4.2.7 on 2026-03-22 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_hotspotsession_is_roaming_hotspotsession_roamed_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fupauditlog',
            name='event_type',
            field=models.CharField(choices=[('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('PLAN_LINKED', 'Plan Linked'), ('PLAN_UNLINKED', 'Plan Unlinked'), ('HOTSPOT_PLAN_LINKED', 'Hotspot Plan Linked'), ('HOTSPOT_PLAN_UNLINKED', 'Hotspot Plan Unlinked'), ('USER_THROTTLED', 'User Throttled'), ('USER_RELEASED', 'User Released'), ('WINDOW_RESET', 'Window Reset')], max_length=40),
        ),
        migrations.CreateModel(
            name='FUPPolicyHotspotPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('hotspot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_policy_links', to='billing.hotspotplan')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_hotspot_plan_links', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_plan_links', to='fup.fuppolicy')),
            ],
            options={
                'verbose_name': 'FUP Policy Hotspot Plan Link',
                'verbose_name_plural': 'FUP Policy Hotspot Plan Links',
                'indexes': [models.Index(fields=['is_active'], name='fup_fuppoli_is_acti_516aed_idx')],
                'unique_together': {('policy', 'hotspot_plan')},
            },
        ),
    ]
