# Generated by Django 4.2.7 on 2026-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fup', '0002_alter_fupauditlog_event_type_fuppolicyhotspotplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fupauditlog',
            name='event_type',
            field=models.CharField(choices=[('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('POLICY_DELETED', 'Policy Deleted'), ('PLAN_LINKED', 'Plan Linked'), ('PLAN_UNLINKED', 'Plan Unlinked'), ('HOTSPOT_PLAN_LINKED', 'Hotspot Plan Linked'), ('HOTSPOT_PLAN_UNLINKED', 'Hotspot Plan Unlinked'), ('USER_THROTTLED', 'User Throttled'), ('USER_RELEASED', 'User Released'), ('WINDOW_RESET', 'Window Reset')], max_length=40),
        ),
    ]
