# Generated by Django 5.2.10 on 2026-05-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_hotspotad_hotspotadgrant_and_more'),
        ('customers', '0004_customer_location_customer_prepaid_credit_and_more'),
        ('fup', '0003_alter_fupauditlog_event_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fupusagewindow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fuppolicy',
            name='peak_hour_end',
            field=models.TimeField(blank=True, help_text='Peak hours end time (24h EAT, Nairobi). e.g. 22:00 = 10 PM', null=True),
        ),
        migrations.AddField(
            model_name='fuppolicy',
            name='peak_hour_start',
            field=models.TimeField(blank=True, help_text='Peak hours start time (24h EAT, Nairobi). e.g. 19:00 = 7 PM', null=True),
        ),
        migrations.AddField(
            model_name='fupthrottlestate',
            name='hotspot_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_throttle_state', to='billing.hotspotsession'),
        ),
        migrations.AddField(
            model_name='fupusagewindow',
            name='hotspot_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_usage_windows', to='billing.hotspotplan'),
        ),
        migrations.AddField(
            model_name='fupusagewindow',
            name='hotspot_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_usage_windows', to='billing.hotspotsession'),
        ),
        migrations.AddField(
            model_name='fupviolation',
            name='hotspot_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_violations', to='billing.hotspotplan'),
        ),
        migrations.AddField(
            model_name='fupviolation',
            name='hotspot_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fup_violations', to='billing.hotspotsession'),
        ),
        migrations.AlterField(
            model_name='fuppolicy',
            name='reset_period',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SUBSCRIPTION', 'Subscription Period'), ('PEAK_HOURS', 'Peak Hours Only')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fupthrottlestate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_throttle_states', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='fupthrottlestate',
            name='service_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_throttle_state', to='customers.serviceconnection'),
        ),
        migrations.AlterField(
            model_name='fupusagewindow',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_usage_windows', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='fupusagewindow',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fup_usage_windows', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='fupusagewindow',
            name='service_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_usage_windows', to='customers.serviceconnection'),
        ),
        migrations.AlterField(
            model_name='fupviolation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_violations', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='fupviolation',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fup_violations', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='fupviolation',
            name='service_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_violations', to='customers.serviceconnection'),
        ),
        migrations.AlterField(
            model_name='fupviolation',
            name='usage_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='fup.fupusagewindow'),
        ),
        migrations.AddIndex(
            model_name='fupusagewindow',
            index=models.Index(fields=['policy', 'service_connection'], name='fup_fupusag_policy__f329d2_idx'),
        ),
        migrations.AddIndex(
            model_name='fupusagewindow',
            index=models.Index(fields=['policy', 'hotspot_session'], name='fup_fupusag_policy__4cdc5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fupusagewindow',
            constraint=models.UniqueConstraint(condition=models.Q(('service_connection__isnull', False)), fields=('policy', 'service_connection', 'period_start', 'period_end'), name='unique_fup_window_pppoe'),
        ),
        migrations.AddConstraint(
            model_name='fupusagewindow',
            constraint=models.UniqueConstraint(condition=models.Q(('hotspot_session__isnull', False)), fields=('policy', 'hotspot_session', 'period_start', 'period_end'), name='unique_fup_window_hotspot'),
        ),
    ]
