# Generated by Django 4.2.7 on 2026-09-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_location_customer_prepaid_credit_and_more'),
        ('billing', '0021_hotspotchatthread_hotspotchatmessage_and_more'),
        ('fup', '0004_alter_fupusagewindow_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUPSessionCounter',
            fields=[
                ('acctuniqueid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('last_input_octets', models.BigIntegerField(default=0)),
                ('last_output_octets', models.BigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='fup_fupsess_usernam_fde6da_idx')],
            },
        ),
        migrations.CreateModel(
            name='FUPUsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('hour_start', models.DateTimeField(db_index=True)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('hotspot_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_buckets', to='billing.hotspotsession')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_buckets', to='fup.fuppolicy')),
                ('service_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fup_buckets', to='customers.serviceconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'hour_start'], name='fup_fupusag_usernam_87eea2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fupusagebucket',
            constraint=models.UniqueConstraint(fields=('policy', 'username', 'hour_start'), name='uniq_fup_bucket_policy_user_hour'),
        ),
    ]