# Generated by Django 5.2.10 on 2026-05-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_hotspotad_hotspotadgrant_and_more'),
        ('customers', '0004_customer_location_customer_prepaid_credit_and_more'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltymember',
            name='hotspot_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_member', to='billing.hotspotclient'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='hotspot_reward_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes of free hotspot internet access for this reward', null=True),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='hotspot_reward_speed_mbps',
            field=models.CharField(blank=True, default='5', help_text='Speed (Mbps) during the reward session, e.g. "5"', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltymember',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_member', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='auto_enroll_new_customers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='program_active',
            field=models.BooleanField(default=False),
        ),
    ]
