# Generated by Django 4.2.7 on 2026-09-30 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_customer_location_customer_prepaid_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPEDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('genieacs_device_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('acs_username', models.CharField(max_length=64, unique=True)),
                ('acs_password', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('oui', models.CharField(blank=True, default='', max_length=32)),
                ('product_class', models.CharField(blank=True, default='', max_length=128)),
                ('software_version', models.CharField(blank=True, default='', max_length=64)),
                ('hardware_version', models.CharField(blank=True, default='', max_length=64)),
                ('data_model', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('never_seen', 'Never seen'), ('online', 'Online'), ('not_answering', 'Not answering')], default='never_seen', max_length=20)),
                ('weak_signal', models.BooleanField(default=False)),
                ('rx_power_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tx_power_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wan_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('inform_interval', models.IntegerField(blank=True, null=True)),
                ('wifi_networks', models.JSONField(blank=True, default=list)),
                ('hosts', models.JSONField(blank=True, default=list)),
                ('last_inform_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_task_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpe_devices', to='customers.customer')),
                ('service_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpe_devices', to='customers.serviceconnection')),
            ],
            options={
                'ordering': ['-last_inform_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPETaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('reboot', 'Reboot'), ('factory_reset', 'Factory Reset'), ('set_wifi', 'Change WiFi'), ('refresh', 'Ask for latest state')], max_length=30)),
                ('genieacs_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tr069_tasks', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='tr069.cpedevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cpedevice',
            index=models.Index(fields=['status'], name='tr069_cpede_status_33bd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='cpedevice',
            index=models.Index(fields=['customer'], name='tr069_cpede_custome_172c82_idx'),
        ),
    ]