# Generated by Django 4.2.7 on 2026-03-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRouterMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_ip', models.GenericIPAddressField(db_index=True, help_text='The VPN IP of the router (e.g., 10.8.0.2)', unique=True)),
                ('nas_secret', models.CharField(help_text='The RADIUS shared secret for this router', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_routers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Global Router Map',
                'verbose_name_plural': 'Global Router Maps',
            },
        ),
    ]
