# Generated by Django 4.2.7 on 2026-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_server', models.CharField(blank=True, max_length=255)),
                ('primary_port', models.IntegerField(default=1812)),
                ('primary_secret', models.CharField(blank=True, max_length=255)),
                ('secondary_server', models.CharField(blank=True, max_length=255)),
                ('secondary_port', models.IntegerField(default=1812)),
                ('secondary_secret', models.CharField(blank=True, max_length=255)),
                ('accounting_port', models.IntegerField(default=1813)),
                ('timeout', models.IntegerField(default=5)),
                ('retries', models.IntegerField(default=3)),
                ('auto_renew', models.BooleanField(default=True)),
                ('auto_expiry', models.BooleanField(default=True)),
                ('auto_notifications', models.BooleanField(default=True)),
                ('auto_backup', models.BooleanField(default=False)),
                ('auto_reports', models.BooleanField(default=True)),
                ('grace_period', models.IntegerField(default=3)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('expiry_notifications', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('sms_gateway', models.CharField(default='africastalking', max_length=50)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
