# Generated by Django 5.2.10 on 2026-04-08 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, help_text='e.g., v1.2.0', max_length=50, null=True)),
                ('content', models.TextField(help_text='Markdown or HTML content of the update')),
                ('update_type', models.CharField(choices=[('feature', 'New Feature'), ('improvement', 'Improvement'), ('bugfix', 'Bug Fix'), ('maintenance', 'Maintenance')], default='feature', max_length=20)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from ISPs as a draft')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Changelog',
                'verbose_name_plural': 'Changelogs',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TumaCallbackMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('network', 'Network & Mikrotik'), ('billing', 'Billing & Payments'), ('hotspot', 'Hotspot & Vouchers'), ('ui_ux', 'Dashboard & UI'), ('automation', 'Automation'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='core.tenant')),
            ],
            options={
                'ordering': ['-upvotes_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalRouterMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_ip', models.GenericIPAddressField(db_index=True, help_text='The VPN IP of the router (e.g., 10.8.0.2)', unique=True)),
                ('nas_secret', models.CharField(help_text='The RADIUS shared secret for this router', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_routers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Global Router Map',
                'verbose_name_plural': 'Global Router Maps',
            },
        ),
        migrations.CreateModel(
            name='FeatureUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='core.featurerequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('feature_request', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='RouterTenantIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('router_auth_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('router_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_tenant_indexes', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Router Tenant Index',
                'verbose_name_plural': 'Router Tenant Indexes',
                'indexes': [models.Index(fields=['tenant_schema'], name='core_router_tenant__7f2bf1_idx'), models.Index(fields=['is_active'], name='core_router_is_acti_d50a8d_idx'), models.Index(fields=['router_id'], name='core_router_router__7b53b0_idx')],
            },
        ),
    ]
