# Generated by Django 4.2.7 on 2026-03-19 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalroutermap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, help_text='e.g., v1.2.0', max_length=50, null=True)),
                ('content', models.TextField(help_text='Markdown or HTML content of the update')),
                ('update_type', models.CharField(choices=[('feature', 'New Feature'), ('improvement', 'Improvement'), ('bugfix', 'Bug Fix'), ('maintenance', 'Maintenance')], default='feature', max_length=20)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from ISPs as a draft')),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Changelog',
                'verbose_name_plural': 'Changelogs',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
