# Generated by Django 4.2.7 on 2026-01-16 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_company_user_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_expiry',
            field=models.DateField(blank=True, help_text='When subscription/trial expires. Auto-calculated on creation.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='Number of days for trial period (default 14)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='When the trial period started (auto-set on creation)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='company',
            field=models.OneToOneField(help_text='The ISP/company this tenant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='core.company'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='database_name',
            field=models.CharField(help_text='Database/schema name prefix or identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='Custom domain if they have one (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='features',
            field=models.JSONField(default=dict, help_text="Enabled features as JSON (e.g. {'analytics': true, 'billing': true})"),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_customers',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_users',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', help_text='Current status of this tenant account', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(help_text='Unique subdomain for this ISP (e.g. bluenet)', max_length=100, unique=True),
        ),
    ]
