# Generated by Django 4.2.7 on 2026-03-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('network', 'Network & Mikrotik'), ('billing', 'Billing & Payments'), ('hotspot', 'Hotspot & Vouchers'), ('ui_ux', 'Dashboard & UI'), ('automation', 'Automation'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='core.tenant')),
            ],
            options={
                'ordering': ['-upvotes_count', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='changelog',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FeatureUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='core.featurerequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('feature_request', 'tenant')},
            },
        ),
    ]
