# Generated by Django 4.2.7 on 2026-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tenant_options_tenant_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Optional. Leave blank if not applicable.', max_length=100, null=True, verbose_name='Registration Number'),
        ),
    ]
