# Generated by Django 4.2.7 on 2026-03-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_featurerequest_alter_changelog_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterTenantIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_auth_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('router_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_tenant_indexes', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Router Tenant Index',
                'verbose_name_plural': 'Router Tenant Indexes',
                'indexes': [models.Index(fields=['tenant_schema'], name='core_router_tenant__7f2bf1_idx'), models.Index(fields=['is_active'], name='core_router_is_acti_d50a8d_idx')],
            },
        ),
    ]
