# Generated by Django 4.2.7 on 2026-03-24 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_routertenantindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='routertenantindex',
            name='router_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='routertenantindex',
            index=models.Index(fields=['router_id'], name='core_router_router__7b53b0_idx'),
        ),
    ]
