# Generated by Django 4.2.7 on 2026-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_routertenantindex_router_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TumaCallbackMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
