# Generated by Django 4.2.7 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changelog_tumacallbackmap_featurerequest_and_more'),
        ('core', '0007_tumacallbackmap'),
    ]

    operations = [
    ]
