# Generated by Django 5.2.10 on 2026-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lead_contacted_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='core_emailo_user_id_9360a5_idx',
            old_name='core_emailot_user_id_fec6cf_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='core_emailo_expires_7a78e9_idx',
            old_name='core_emailot_expires_216fdb_idx',
        ),
        migrations.RenameIndex(
            model_name='loginotpchallenge',
            new_name='core_logino_user_id_e856a8_idx',
            old_name='core_loginot_user_id_e201ca_idx',
        ),
        migrations.RenameIndex(
            model_name='loginotpchallenge',
            new_name='core_logino_tenant__86760b_idx',
            old_name='core_loginot_tenant__a61194_idx',
        ),
        migrations.RenameIndex(
            model_name='loginotpchallenge',
            new_name='core_logino_expires_4ccd10_idx',
            old_name='core_loginot_expires_8ec9a1_idx',
        ),
        migrations.RenameIndex(
            model_name='routertenantindex',
            new_name='core_router_tenant__8526ca_idx',
            old_name='core_router_tenant__b3e645_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
