# Generated by Django 4.2.7 on 2026-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lead_referral_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsystemsettings',
            name='hide_lower_plans_in_customer_portal',
            field=models.BooleanField(default=False),
        ),
    ]
