# Generated by Django 4.2.7 on 2026-07-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_company_country_base_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.CharField(default='KES', help_text='Base currency for this company, derived from country at creation', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('KE', 'Kenya'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('TZ', 'Tanzania'), ('UG', 'Uganda')], default='KE', help_text='Country this ISP company operates in', max_length=2),
        ),
    ]