# Generated by Django 4.2.7 on 2026-07-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_globalsystemsettings_affiliate_email_otp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaShortcodeTenantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_shortcode', models.CharField(db_index=True, max_length=20)),
                ('shortcode_type', models.CharField(max_length=10)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Shortcode Tenant Map',
                'verbose_name_plural': 'M-Pesa Shortcode Tenant Maps',
                'indexes': [models.Index(fields=['business_shortcode', 'is_active'], name='core_mpesas_busines_6b47f9_idx')],
                'unique_together': {('business_shortcode', 'shortcode_type')},
            },
        ),
    ]