# Generated by Django 5.2.10 on 2026-09-14 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_emailotp_affiliate_password_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('tenant_name', models.CharField(blank=True, default='', max_length=255)),
                ('tenant_subdomain', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='General', max_length=80)),
                ('subject', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('waiting_on_tenant', 'Waiting on tenant'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=32)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=160)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_by_phone', models.CharField(blank=True, default='', max_length=32)),
                ('assigned_to_user_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=160)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=260)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('superadmin_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='core_suppor_tenant__2424f2_idx'), models.Index(fields=['status', 'last_message_at'], name='core_suppor_status_646fd6_idx'), models.Index(fields=['assigned_to_user_id', 'status'], name='core_suppor_assigne_0252d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('tenant', 'Tenant'), ('superadmin', 'Superadmin'), ('system', 'System')], db_index=True, max_length=20)),
                ('sender_user_id', models.IntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=160)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportchatconversation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='core_suppor_convers_0f9384_idx'), models.Index(fields=['sender_type', 'created_at'], name='core_suppor_sender__e4a2b5_idx')],
            },
        ),
    ]
