# Generated by Django 4.2.7 on 2026-09-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_supportchatconversation_supportchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tr069DeviceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('genieacs_device_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('acs_username', models.CharField(max_length=64, unique=True)),
                ('acs_password', models.CharField(max_length=64)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr069_device_indexes', to='core.tenant')),
            ],
            options={
                'verbose_name': 'TR-069 Device Index',
                'verbose_name_plural': 'TR-069 Device Indexes',
                'indexes': [models.Index(fields=['tenant_schema'], name='core_tr069d_tenant__a11c1d_idx')],
            },
        ),
    ]