# Generated by Django 5.2.10 on 2026-01-29 08:50

import apps.vpn.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0004_remove_hotspotuser_network_hot_last_se_292ec0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('common_name', models.CharField(help_text='CN for the CA certificate', max_length=100)),
                ('organization', models.CharField(blank=True, default='Netily ISP', max_length=100)),
                ('country', models.CharField(default='KE', help_text='2-letter country code', max_length=2)),
                ('ca_certificate', models.TextField(help_text='PEM-encoded CA certificate')),
                ('ca_private_key', models.TextField(help_text='PEM-encoded CA private key (encrypted)')),
                ('dh_parameters', models.TextField(blank=True, help_text='DH parameters for OpenVPN')),
                ('tls_auth_key', models.TextField(blank=True, help_text='OpenVPN TLS Auth key')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('validity_days', models.IntegerField(default=3650, help_text='CA validity in days (default 10 years)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPNCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_name', models.CharField(help_text='CN for the certificate', max_length=100)),
                ('certificate_type', models.CharField(choices=[('client', 'Client Certificate'), ('server', 'Server Certificate')], default='client', max_length=10)),
                ('serial_number', models.CharField(default=apps.vpn.models.generate_serial_number, max_length=64, unique=True)),
                ('certificate', models.TextField(blank=True, help_text='PEM-encoded certificate')),
                ('private_key', models.TextField(blank=True, help_text='PEM-encoded private key (encrypted)')),
                ('certificate_request', models.TextField(blank=True, help_text='CSR if using external signing')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('validity_days', models.IntegerField(default=365, help_text='Certificate validity in days')),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='vpn.certificateauthority')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpn_certificates', to='network.router')),
            ],
            options={
                'verbose_name': 'VPN Certificate',
                'verbose_name_plural': 'VPN Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPNConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vpn_ip', models.GenericIPAddressField(blank=True, help_text='Assigned VPN IP', null=True)),
                ('real_ip', models.GenericIPAddressField(blank=True, help_text="Router's public IP", null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('error', 'Error')], default='disconnected', max_length=15)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='vpn.vpncertificate')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_connections', to='network.router')),
            ],
            options={
                'verbose_name': 'VPN Connection',
                'verbose_name_plural': 'VPN Connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='VPNConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('connect', 'Connected'), ('disconnect', 'Disconnected'), ('auth_success', 'Authentication Success'), ('auth_failure', 'Authentication Failure'), ('cert_verify', 'Certificate Verified'), ('cert_error', 'Certificate Error'), ('ip_assigned', 'IP Assigned'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('vpn_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('real_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='vpn.vpnconnection')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_logs', to='network.router')),
            ],
            options={
                'verbose_name': 'VPN Connection Log',
                'verbose_name_plural': 'VPN Connection Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Primary VPN Server', max_length=100)),
                ('server_address', models.CharField(help_text='Public hostname or IP', max_length=255)),
                ('port', models.IntegerField(default=1194, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=3)),
                ('vpn_network', models.CharField(default='10.8.0.0/24', help_text='VPN subnet CIDR', max_length=18)),
                ('dns_servers', models.CharField(default='8.8.8.8,8.8.4.4', help_text='Comma-separated DNS servers', max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('starting', 'Starting'), ('error', 'Error')], default='stopped', max_length=10)),
                ('max_clients', models.IntegerField(default=100)),
                ('connected_clients', models.IntegerField(default=0)),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID', max_length=64)),
                ('container_name', models.CharField(default='openvpn-server', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_status_check', models.DateTimeField(blank=True, null=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_servers', to='vpn.certificateauthority')),
                ('certificate', models.ForeignKey(blank=True, limit_choices_to={'certificate_type': 'server'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='vpn.vpncertificate')),
            ],
            options={
                'verbose_name': 'VPN Server',
                'verbose_name_plural': 'VPN Servers',
            },
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='vpn.vpnserver'),
        ),
        migrations.AddIndex(
            model_name='vpncertificate',
            index=models.Index(fields=['router', 'status'], name='vpn_vpncert_router__e952e8_idx'),
        ),
        migrations.AddIndex(
            model_name='vpncertificate',
            index=models.Index(fields=['certificate_type', 'status'], name='vpn_vpncert_certifi_32a65a_idx'),
        ),
        migrations.AddIndex(
            model_name='vpncertificate',
            index=models.Index(fields=['serial_number'], name='vpn_vpncert_serial__64cad8_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnectionlog',
            index=models.Index(fields=['router', 'event_type'], name='vpn_vpnconn_router__655e81_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnectionlog',
            index=models.Index(fields=['created_at'], name='vpn_vpnconn_created_38fc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnection',
            index=models.Index(fields=['router', 'status'], name='vpn_vpnconn_router__07bc02_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnection',
            index=models.Index(fields=['server', 'status'], name='vpn_vpnconn_server__cdb332_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnection',
            index=models.Index(fields=['vpn_ip'], name='vpn_vpnconn_vpn_ip_f6bae1_idx'),
        ),
    ]
