from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from .models.billing_models import Invoice, InvoiceItem
from .models.payment_models import Payment
from .models.voucher_models import Voucher
from .integrations.africastalking import SMSService
import logging

logger = logging.getLogger(__name__)


@receiver(pre_save, sender=Invoice)
def calculate_invoice_totals(sender, instance, **kwargs):
    """Calculate invoice totals before saving"""
    # Track if status changed for use in post_save
    if instance.pk:
        try:
            old_instance = sender.objects.get(pk=instance.pk)
            instance._status_changed = (old_instance.status != instance.status)
        except sender.DoesNotExist:
            instance._status_changed = False
    else:
        instance._status_changed = True
    
    if instance.pk:
        # Update totals based on items
        items = instance.items.all()
        instance.subtotal = sum(item.total for item in items)
        instance.tax_amount = sum(item.tax_amount for item in items)
        instance.total_amount = instance.subtotal + instance.tax_amount - instance.discount_amount
        instance.balance = instance.total_amount - instance.amount_paid


@receiver(post_save, sender=Payment)
def handle_payment_completion(sender, instance, created, **kwargs):
    """Handle actions when payment is completed"""
    if not created and instance.status == 'COMPLETED':
        # Update customer balance
        customer = instance.customer
        if customer:
            from decimal import Decimal
            customer.outstanding_balance = max(
                Decimal('0'),
                (customer.outstanding_balance or Decimal('0')) - instance.amount
            )
            customer.save(update_fields=['outstanding_balance', 'updated_at'])
        
        # Update invoice if exists
        if instance.invoice:
            invoice = instance.invoice
            invoice.amount_paid += instance.amount
            invoice.balance = invoice.total_amount - invoice.amount_paid
            
            if invoice.balance <= 0:
                invoice.status = 'PAID'
                invoice.paid_at = timezone.now()
                invoice.paid_by = instance.created_by
            
            invoice.save()

        # ── SMS: payment confirmation (uses SMSNotifier with internal toggle checks) ──
        if customer:
            try:
                from apps.messaging.services.notification_sender import SMSNotifier
                SMSNotifier.pppoe_payment(
                    customer=customer,
                    amount=float(instance.amount),
                    reference=instance.payment_reference or instance.mpesa_receipt or '',
                )
            except Exception as e:
                logger.warning(f"Payment confirmation SMS failed: {e}")

        # Email confirmation (async)
        if customer:
            try:
                from django.db import connection
                from apps.billing.tasks import send_payment_confirmation_email
                send_payment_confirmation_email.delay(
                    customer_id=customer.id,
                    amount=float(instance.amount),
                    reference=instance.payment_reference or '',
                    payment_method=str(instance.payment_method) if instance.payment_method else '',
                    tenant_schema=connection.schema_name,
                )
            except Exception as e:
                logger.warning(f"Payment email task failed: {e}")


@receiver(post_save, sender=Voucher)
def handle_voucher_sale(sender, instance, created, **kwargs):
    """Handle actions when voucher is sold"""
    if instance.sold_to and instance.sold_at:
        # Send voucher PIN via SMS using SMSNotifier
        try:
            from apps.messaging.services.notification_sender import SMSNotifier
            # Check if the voucher is for hotspot or PPPoE
            if hasattr(instance, 'batch') and instance.batch and instance.batch.hotspot_plan:
                # Hotspot voucher
                SMSNotifier.hotspot_voucher_sold(instance)
            else:
                # Generic voucher
                SMSNotifier.voucher_sold(instance)
        except Exception as e:
            logger.warning(f"Voucher SMS failed: {e}")


@receiver(post_save, sender=Invoice)
def send_invoice_notification(sender, instance, created, **kwargs):
    """
    Send notification when invoice is issued.
    
    Fires when:
    1. A new invoice is created with status 'ISSUED' (created=True)
    2. An existing draft invoice is updated to 'ISSUED' (status changed)
    
    This ensures that invoices generated by the metered billing system
    (which are created directly as ISSUED) will send notifications.
    """
    # Only send notification when invoice status is ISSUED
    if instance.status == 'ISSUED':
        # Check if this is either:
        # - A newly created invoice (created=True)
        # - An existing invoice that just had its status changed to ISSUED
        status_just_changed = getattr(instance, '_status_changed', False)
        
        if created or status_just_changed:
            try:
                # Get the customer
                customer = instance.customer
                if customer:
                    # Use SMSNotifier for invoice notification
                    from apps.messaging.services.notification_sender import SMSNotifier
                    SMSNotifier.pppoe_invoice_issued(customer, instance)
            except Exception as e:
                logger.error(f"Failed to send invoice notification: {e}")