server 10.8.0.0 255.255.0.0
verb 3
port 1194
proto udp
dev tun0
topology subnet

# Identity - These paths MUST match the specific certificate files on your VPS
key /etc/openvpn/pki/private/68.183.45.64.key
ca /etc/openvpn/pki/ca.crt
cert /etc/openvpn/pki/issued/68.183.45.64.crt
dh /etc/openvpn/pki/dh.pem

keepalive 10 60
persist-key
persist-tun

push "topology subnet"
push "route-gateway 10.8.0.1"
push "route 10.8.0.0 255.255.0.0"
push "dhcp-option DNS 8.8.8.8"

# Security & Authentication
cipher AES-256-CBC
auth-user-pass-verify /etc/openvpn/check_auth.sh via-env
script-security 3
verify-client-cert none
username-as-common-name

status /tmp/openvpn-status.log
user nobody
group nogroup
# Enable management interface so Django/Celery can talk to OpenVPN
management 0.0.0.0 7505