# Generated by Django 4.2.7 on 2025-12-31 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('data', 'Data Usage'), ('billing', 'Billing'), ('payment', 'Payment'), ('service', 'Service')], max_length=50)),
                ('trigger_type', models.CharField(choices=[('threshold', 'Threshold Reached'), ('due_date', 'Due Date Approaching'), ('overdue', 'Payment Overdue'), ('limit_exceeded', 'Limit Exceeded')], max_length=50)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_alerts', to='customers.customer')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['customer', 'is_read'], name='self_servic_custome_cbe1ff_idx'), models.Index(fields=['alert_type', 'triggered_at'], name='self_servic_alert_t_16f08c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('connection', 'New Connection'), ('upgrade', 'Plan Upgrade'), ('downgrade', 'Plan Downgrade'), ('transfer', 'Location Transfer'), ('suspension', 'Service Suspension'), ('termination', 'Service Termination'), ('billing', 'Billing Issue'), ('technical', 'Technical Support'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('current_location', models.TextField(blank=True)),
                ('requested_location', models.TextField(blank=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to='billing.plan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='customers.customer')),
                ('requested_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_requests', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='self_servic_custome_a70fba_idx'), models.Index(fields=['request_type', 'status'], name='self_servic_request_bcecd8_idx'), models.Index(fields=['created_at'], name='self_servic_created_c091b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='customers.customer')),
            ],
            options={
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['customer', 'login_time'], name='self_servic_custome_badd91_idx'), models.Index(fields=['is_active', 'last_activity'], name='self_servic_is_acti_2b10af_idx')],
            },
        ),
    ]
