# Generated by Django 5.2.10 on 2026-01-22 07:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetilyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, help_text='Short marketing tagline', max_length=255)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('max_subscribers', models.PositiveIntegerField(help_text='Maximum number of ISP subscribers allowed. 0 = unlimited')),
                ('max_routers', models.PositiveIntegerField(help_text='Maximum number of routers allowed. 0 = unlimited')),
                ('max_staff', models.PositiveIntegerField(help_text='Maximum number of staff accounts allowed. 0 = unlimited')),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'Popular' badge")),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Netily Plan',
                'verbose_name_plural': 'Netily Plans',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='ISPPayoutConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_method', models.CharField(choices=[('mpesa_b2c', 'M-Pesa (Mobile Money)'), ('bank_transfer', 'Bank Transfer')], default='mpesa_b2c', max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15)),
                ('mpesa_name', models.CharField(blank=True, help_text='Verified M-Pesa registered name', max_length=100)),
                ('bank_code', models.CharField(blank=True, choices=[('kcb', 'Kenya Commercial Bank (KCB)'), ('equity', 'Equity Bank'), ('coop', 'Co-operative Bank'), ('stanbic', 'Stanbic Bank'), ('dtb', 'Diamond Trust Bank'), ('absa', 'ABSA Bank Kenya'), ('scb', 'Standard Chartered'), ('ncba', 'NCBA Bank'), ('im', 'I&M Bank'), ('family', 'Family Bank'), ('other', 'Other')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_swift_code', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount sent for verification', max_digits=10, null=True)),
                ('settlement_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum amount before settlement is triggered', max_digits=10)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_config', to='core.company')),
            ],
            options={
                'verbose_name': 'ISP Payout Configuration',
                'verbose_name_plural': 'ISP Payout Configurations',
            },
        ),
        migrations.CreateModel(
            name='ISPSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total amount collected from customers', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Netily commission rate (default 5%)', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text="Netily's commission", max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount paid to ISP (gross - commission)', max_digits=12)),
                ('payout_method', models.CharField(max_length=20)),
                ('payout_destination', models.CharField(help_text='M-Pesa phone or bank account', max_length=255)),
                ('payout_reference', models.CharField(blank=True, help_text='PayHero transaction reference', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('transaction_count', models.PositiveIntegerField(default=0, help_text='Number of customer payments in this settlement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.company')),
            ],
            options={
                'verbose_name': 'ISP Settlement',
                'verbose_name_plural': 'ISP Settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('hotspot', 'Hotspot Purchase'), ('recharge', 'Account Recharge'), ('invoice', 'Invoice Payment')], max_length=20)),
                ('payment_reference', models.CharField(help_text='Original payment reference', max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='core.company')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='subscriptions.ispsettlement')),
            ],
            options={
                'verbose_name': 'Commission Entry',
                'verbose_name_plural': 'Commission Ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trialing', 'Trial')], default='active', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.netilyplan')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa_stk', 'M-Pesa STK Push'), ('mpesa_paybill', 'M-Pesa Paybill'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], default='mpesa_stk', max_length=20)),
                ('payhero_checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payhero_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.companysubscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
