# Generated by Django 4.2.7 on 2026-03-19 12:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalroutermap'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netilyplan',
            name='base_license_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='hotspot_revenue_share_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='is_metered',
            field=models.BooleanField(default=False, help_text='If True, uses dynamic metered billing instead of flat price_monthly'),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='pppoe_min_clients',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='pppoe_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='active', max_length=20)),
                ('hotspot_revenue_accumulated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='subscriptions.companysubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BillableClientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billable_clients', to='subscriptions.billingcycle')),
            ],
            options={
                'verbose_name': 'Billable Client Record',
                'verbose_name_plural': 'Billable Client Records',
                'indexes': [models.Index(fields=['cycle', 'username'], name='subscriptio_cycle_i_918fec_idx')],
                'unique_together': {('cycle', 'username')},
            },
        ),
    ]
