# Generated by Django 5.2.10 on 2026-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='converted_from_trial_at',
            field=models.DateTimeField(blank=True, help_text='When trial converted to paid subscription', null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='is_trial',
            field=models.BooleanField(default=True, help_text='Whether this subscription is on free trial'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the trial expires', null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When the trial started', null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trialing', 'Trial')], default='trialing', max_length=20),
        ),
    ]
