# Generated by Django 5.2.10 on 2026-04-08 14:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changelog_tumacallbackmap_featurerequest_and_more'),
        ('subscriptions', '0002_companysubscription_converted_from_trial_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netilyplan',
            name='base_license_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='hotspot_revenue_share_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='is_metered',
            field=models.BooleanField(default=False, help_text='If True, uses dynamic metered billing instead of flat price_monthly'),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='pppoe_min_clients',
            field=models.PositiveIntegerField(default=20, help_text='Minimum billable PPPoE clients per cycle (floor). ISPs with fewer active clients are still billed for this many.'),
        ),
        migrations.AddField(
            model_name='netilyplan',
            name='pppoe_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payhero_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='active', max_length=20)),
                ('hotspot_revenue_accumulated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('snapshot_pppoe_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('snapshot_min_clients', models.PositiveIntegerField(default=20, help_text='Minimum billable PPPoE clients (floor)')),
                ('snapshot_hotspot_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('grace_ends_at', models.DateTimeField(blank=True, help_text='When the 4-day grace period expires. Set when invoice is generated.', null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='subscriptions.companysubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BillableClientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billable_clients', to='subscriptions.billingcycle')),
            ],
            options={
                'verbose_name': 'Billable Client Record',
                'verbose_name_plural': 'Billable Client Records',
                'indexes': [models.Index(fields=['cycle', 'username'], name='subscriptio_cycle_i_918fec_idx')],
                'unique_together': {('cycle', 'username')},
            },
        ),
        migrations.CreateModel(
            name='BillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='subscriptions.billingcycle')),
            ],
            options={
                'verbose_name': 'Billing Snapshot',
                'verbose_name_plural': 'Billing Snapshots',
                'indexes': [models.Index(fields=['cycle', 'username'], name='subscriptio_cycle_i_cb9da7_idx')],
                'unique_together': {('cycle', 'username')},
            },
        ),
    ]
