# Generated by Django 4.2.7 on 2026-03-19 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_netilyplan_base_license_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='snapshot_base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='snapshot_hotspot_share_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='snapshot_min_clients',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='snapshot_pppoe_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
