# Generated by Django 4.2.7 on 2026-03-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_billingcycle_snapshot_base_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='subscriptions.billingcycle')),
            ],
            options={
                'verbose_name': 'Billing Snapshot',
                'verbose_name_plural': 'Billing Snapshots',
                'indexes': [models.Index(fields=['cycle', 'username'], name='subscriptio_cycle_i_cb9da7_idx')],
                'unique_together': {('cycle', 'username')},
            },
        ),
    ]
