# Generated by Django 5.2.10 on 2026-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_netilyplan_base_license_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netilyplan',
            name='code',
            field=models.CharField(choices=[('metered', 'Metered'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=50, unique=True),
        ),
    ]
