# Generated by Django 4.2.7 on 2026-03-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_billingsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcycle',
            name='snapshot_min_clients',
        ),
        migrations.RemoveField(
            model_name='netilyplan',
            name='pppoe_min_clients',
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payhero_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
