# Generated by Django 5.2.10 on 2026-04-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_netilyplan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='intended_billing_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Billing period to apply upon successful payment', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='intended_plan',
            field=models.ForeignKey(blank=True, help_text='Plan to switch to upon successful payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_payments', to='subscriptions.netilyplan'),
        ),
    ]
