# Generated by Django 4.2.7 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_netilyplan_base_license_fee_and_more'),
        ('subscriptions', '0005_remove_billingcycle_snapshot_min_clients_and_more'),
    ]

    operations = [
    ]
