# Generated by Django 5.2.10 on 2026-04-19 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lead_message'),
        ('subscriptions', '0005_subscriptionpayment_intended_billing_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='is_first_paid_cycle',
            field=models.BooleanField(default=False, help_text='True for the first cycle after trial conversion. Only base license fee is charged.'),
        ),
        migrations.CreateModel(
            name='TenantUserLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('customer_created', 'Customer Created'), ('customer_deleted', 'Customer Deleted'), ('service_created', 'Service Created'), ('service_deleted', 'Service Deleted'), ('service_activated', 'Service Activated'), ('service_suspended', 'Service Suspended'), ('service_terminated', 'Service Terminated')], db_index=True, max_length=30)),
                ('user_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('static', 'Static IP'), ('dhcp', 'DHCP'), ('other', 'Other')], default='pppoe', max_length=20)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, db_index=True, help_text='PPPoE/Hotspot username at the time of the event', max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('pppoe_count_after', models.PositiveIntegerField(default=0, help_text='Total active PPPoE services in tenant after this event')),
                ('hotspot_count_after', models.PositiveIntegerField(default=0, help_text='Total active hotspot services in tenant after this event')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ledger_entries', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant User Ledger Entry',
                'verbose_name_plural': 'Tenant User Ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'event'], name='subscriptio_tenant__e204ee_idx'), models.Index(fields=['tenant', 'created_at'], name='subscriptio_tenant__add8a1_idx')],
            },
        ),
    ]
