# Generated by Django 5.2.10 on 2026-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_billingcycle_is_first_paid_cycle_tenantuserledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='defer_billing_to_trial_end',
            field=models.BooleanField(default=False, help_text='If True, billing cycle starts when trial ends instead of now'),
        ),
    ]
