# Generated by Django 5.2.10 on 2026-06-22 19:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_netilyplan_pppoe_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='netilyplan',
            name='activation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='One-time fee charged when a trial converts to a paid subscription (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='netilyplan',
            name='code',
            field=models.CharField(choices=[('starter', 'Starter'), ('enterprise', 'Enterprise'), ('metered', 'Metered (legacy)'), ('professional', 'Professional (legacy)')], max_length=50, unique=True),
        ),
    ]
