# Generated by Codex on 2026-09-03

from django.db import migrations, models


def backfill_billing_anchor_day(apps, schema_editor):
    CompanySubscription = apps.get_model("subscriptions", "CompanySubscription")
    SubscriptionPayment = apps.get_model("subscriptions", "SubscriptionPayment")

    for subscription in CompanySubscription.objects.filter(billing_anchor_day__isnull=True):
        latest_payment = (
            SubscriptionPayment.objects
            .filter(subscription_id=subscription.id, status="completed", completed_at__isnull=False)
            .order_by("-completed_at", "-created_at")
            .first()
        )
        anchor_source = (
            latest_payment.completed_at
            if latest_payment
            else subscription.current_period_start or subscription.current_period_end
        )
        if anchor_source:
            subscription.billing_anchor_day = max(1, min(31, int(anchor_source.day)))
            subscription.save(update_fields=["billing_anchor_day"])


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_add_activation_fee_update_plan_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysubscription",
            name="billing_anchor_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Calendar day used for recurring subscription renewals. Set from the first paid activation date.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_billing_anchor_day, migrations.RunPython.noop),
    ]
