# Generated by Django 4.2.7 on 2026-09-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_companysubscription_billing_anchor_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Hi {admin_name}, your Netily subscription for {company_name} ({plan_name}) is due in {days_left} day(s) on {expiry_date}. Amount due: KES {amount_due}. Please pay to avoid service interruption.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Reminder Template',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('3_day', '3 Days Before'), ('1_day', '1 Day Before')], max_length=10)),
                ('period_end', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='subscriptions.companysubscription')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['subscription', 'milestone'], name='subscriptio_subscri_c3ed54_idx')],
                'unique_together': {('subscription', 'milestone', 'period_end')},
            },
        ),
    ]