# Generated by Django 4.2.7 on 2026-03-02 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_id_number'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_type', models.CharField(choices=[('basic', 'Basic Router'), ('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('isp', 'Full ISP (Hotspot + PPPoE)'), ('full_isp', 'Full ISP with OpenVPN')], max_length=20)),
                ('config_data', models.JSONField(default=dict, help_text='Configuration parameters')),
                ('config_script', models.TextField(help_text='Generated RouterOS script')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.CharField(blank=True, max_length=100, null=True)),
                ('schema_name', models.SlugField(blank=True, editable=False, max_length=63, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='router',
            name='network_rou_last_se_746cd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='router',
            name='network_rou_company_e9c5cb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ippool',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='schema_name',
        ),
        migrations.RemoveField(
            model_name='router',
            name='company',
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='connected_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Customer currently holding this IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ips', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='broadcast_address',
            field=models.GenericIPAddressField(blank=True, help_text='Broadcast address (e.g. 10.50.3.255)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='cidr_prefix',
            field=models.IntegerField(blank=True, choices=[(24, '/24 — 254 usable IPs'), (25, '/25 — 126 usable IPs'), (26, '/26 — 62 usable IPs'), (27, '/27 — 30 usable IPs'), (28, '/28 — 14 usable IPs'), (29, '/29 — 6 usable IPs'), (30, '/30 — 2 usable IPs')], default=24, help_text='CIDR mask: /24=254 IPs, /25=126, /26=62, etc.', null=True),
        ),
        migrations.AddField(
            model_name='ippool',
            name='network_address',
            field=models.GenericIPAddressField(blank=True, help_text='Network address (e.g. 10.50.3.0)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='router',
            field=models.ForeignKey(blank=True, help_text='The physical router (NAS) this pool exists on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_pools', to='network.router'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='subnet_octet',
            field=models.IntegerField(blank=True, help_text='Third octet (0-255), e.g. 3 → 10.50.3.x', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='ippool',
            name='subnet_prefix',
            field=models.CharField(blank=True, choices=[('10.0', '10.0.x.x'), ('10.20', '10.20.x.x'), ('10.30', '10.30.x.x'), ('10.40', '10.40.x.x'), ('10.50', '10.50.x.x (Netily Standard)'), ('10.60', '10.60.x.x'), ('10.70', '10.70.x.x'), ('10.80', '10.80.x.x'), ('10.90', '10.90.x.x'), ('10.100', '10.100.x.x'), ('10.110', '10.110.x.x'), ('10.120', '10.120.x.x'), ('172.16', '172.16.x.x'), ('172.17', '172.17.x.x'), ('172.19', '172.19.x.x'), ('172.20', '172.20.x.x'), ('172.24', '172.24.x.x'), ('172.28', '172.28.x.x'), ('172.31', '172.31.x.x'), ('192.168.0', '192.168.0.x (⚠ Home conflict)'), ('192.168.1', '192.168.1.x (⚠ Home conflict)'), ('192.168.10', '192.168.10.x'), ('192.168.100', '192.168.100.x')], help_text='First two octets, e.g. 10.50 → 10.50.x.x', max_length=15),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='connected_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='announcement_text',
            field=models.CharField(blank=True, default='', help_text="Short banner message on the captive portal (e.g. 'Buy 24h for KES 50!')", max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='ca_certificate',
            field=models.TextField(blank=True, help_text="PEM content of ca.crt for this router's VPN", null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='client_certificate',
            field=models.TextField(blank=True, help_text='PEM content of client.crt', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='client_key',
            field=models.TextField(blank=True, help_text='PEM content of client.key (should be encrypted at rest)', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='config_type',
            field=models.CharField(choices=[('basic', 'Basic Router'), ('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('isp', 'Full ISP (Hotspot + PPPoE)'), ('full_isp', 'Full ISP with OpenVPN')], default='isp', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='dns_name',
            field=models.CharField(default='captive.netily.io', help_text='DNS name for the hotspot (e.g., login.wifi)', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='enable_hotspot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='router',
            name='enable_openvpn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='router',
            name='enable_pppoe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='router',
            name='gateway_cidr',
            field=models.CharField(default='172.18.0.1/16', help_text='The main Gateway IP/Subnet (e.g., 172.18.0.1/16). Pool is calculated from this.', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_base_ip',
            field=models.GenericIPAddressField(default='172.12.0.1', help_text='Gateway IP for the hotspot network (e.g., 172.12.0.1)'),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_cookie_lifetime',
            field=models.CharField(default='4w2d', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_interfaces',
            field=models.JSONField(blank=True, default=list, help_text='List of interfaces assigned to the Hotspot Bridge'),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_name',
            field=models.CharField(blank=True, default='', help_text="Display name on the captive portal (e.g. 'Mjengo Fast Wi-Fi')", max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_portal_url',
            field=models.URLField(default='https://app.yourisp.local'),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_ssl_cert',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_subnet',
            field=models.CharField(default='172.19.0.0/16', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_subnet_cidr',
            field=models.IntegerField(default=16, help_text='CIDR prefix length for hotspot subnet (e.g., 16 = /16 = 65,534 hosts)', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='router',
            name='lan_interfaces',
            field=models.CharField(default='ether2,ether3', max_length=200),
        ),
        migrations.AddField(
            model_name='router',
            name='lan_subnet',
            field=models.CharField(default='192.168.88.0/24', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='last_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_port',
            field=models.IntegerField(default=1194),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_server',
            field=models.CharField(default='vpn.yourisp.com', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='pppoe_local_address',
            field=models.GenericIPAddressField(blank=True, default='192.40.2.1', help_text='PPPoE server local address (service-name gateway)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='router',
            name='pppoe_pool',
            field=models.CharField(default='192.40.2.10-192.40.2.254', max_length=50),
        ),
        migrations.AddField(
            model_name='router',
            name='provision_slug',
            field=models.SlugField(blank=True, help_text='Short URL-safe slug for magic-link downloads (auto-generated)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_port',
            field=models.IntegerField(default=1812),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_server',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='router',
            name='routeros_version',
            field=models.CharField(blank=True, help_text='Detected RouterOS major version (6 or 7)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_certificate',
            field=models.TextField(blank=True, help_text='PEM content of SSL cert for hotspot HTTPS (e.g. *.yourisp.com)', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_passphrase',
            field=models.CharField(blank=True, default='', help_text='Passphrase for the SSL key (if encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_private_key',
            field=models.TextField(blank=True, help_text='PEM content of SSL private key', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='support_phone',
            field=models.CharField(blank=True, default='', help_text='Customer-care phone shown on captive portal', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='template_id',
            field=models.IntegerField(default=1, help_text='UI template for captive portal (1-7)'),
        ),
        migrations.AddField(
            model_name='router',
            name='tenant_subdomain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
