# Generated by Django 4.2.7 on 2026-01-06 09:14

import apps.network.models.router_models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('api_port', models.PositiveIntegerField(default=8728, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('api_username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_password', models.CharField(blank=True, max_length=255, null=True)),
                ('router_type', models.CharField(choices=[('mikrotik', 'Mikrotik'), ('ubiquiti', 'Ubiquiti'), ('cisco', 'Cisco'), ('other', 'Other')], default='mikrotik', max_length=50)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('warning', 'Warning'), ('error', 'Error')], default='offline', max_length=20)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('uptime', models.CharField(blank=True, max_length=50, null=True)),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sla_target', models.DecimalField(decimal_places=2, default=99.0, max_digits=5)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_key', models.CharField(default=apps.network.models.router_models.generate_auth_key, max_length=50, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('up', 'Router Online'), ('down', 'Router Offline'), ('reboot', 'Router Rebooted'), ('config_change', 'Configuration Changed'), ('warning', 'Warning'), ('error', 'Error'), ('maintenance', 'Maintenance Mode'), ('auth_success', 'Authenticated Successfully'), ('auth_key_regen', 'Auth Key Regenerated'), ('backup', 'Backup Created')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mikrotikdevice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='mikrotikdevice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mikrotikdevice',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='hotspotuser',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='mikrotikinterface',
            options={'ordering': ['interface_name']},
        ),
        migrations.AlterModelOptions(
            name='mikrotikqueue',
            options={'ordering': ['queue_name']},
        ),
        migrations.AlterModelOptions(
            name='pppoeuser',
            options={'ordering': ['username']},
        ),
        migrations.RemoveIndex(
            model_name='hotspotuser',
            name='network_hot_usernam_78c150_idx',
        ),
        migrations.RemoveIndex(
            model_name='hotspotuser',
            name='network_hot_status_a94eed_idx',
        ),
        migrations.RemoveIndex(
            model_name='hotspotuser',
            name='network_hot_last_lo_36f11d_idx',
        ),
        migrations.AlterField(
            model_name='mikrotikinterface',
            name='interface_type',
            field=models.CharField(choices=[('ETHERNET', 'Ethernet'), ('WLAN', 'Wireless'), ('BRIDGE', 'Bridge'), ('VLAN', 'VLAN'), ('PPPOE', 'PPPoE'), ('OTHER', 'Other')], default='ETHERNET', max_length=20),
        ),
        migrations.AlterField(
            model_name='mikrotikqueue',
            name='hotspot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.hotspotuser'),
        ),
        migrations.AlterField(
            model_name='mikrotikqueue',
            name='pppoe_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.pppoeuser'),
        ),
        migrations.AlterField(
            model_name='mikrotikqueue',
            name='queue_type',
            field=models.CharField(default='SIMPLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pppoeuser',
            name='status',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('DISABLED', 'Disabled')], default='DISCONNECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='routerevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routerevent',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='network.router'),
        ),
        migrations.AddField(
            model_name='routerevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='router',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='core.company'),
        ),
        migrations.AddField(
            model_name='router',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='router',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hotspotuser',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mikrotikinterface',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mikrotikqueue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pppoeuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='router',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_users', to='network.router'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mikrotikinterface',
            name='router',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='network.router'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mikrotikqueue',
            name='router',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='network.router'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='router',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_users', to='network.router'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hotspotuser',
            unique_together={('router', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='mikrotikinterface',
            unique_together={('router', 'interface_name')},
        ),
        migrations.AlterUniqueTogether(
            name='mikrotikqueue',
            unique_together={('router', 'queue_name')},
        ),
        migrations.AlterUniqueTogether(
            name='pppoeuser',
            unique_together={('router', 'username')},
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['ip_address'], name='network_rou_ip_addr_4854e3_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['status'], name='network_rou_status_ebb1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['last_seen'], name='network_rou_last_se_746cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['auth_key'], name='network_rou_auth_ke_d6b01f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='router',
            unique_together={('company', 'name')},
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='idle_time',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='last_logout',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='limit_bytes_in',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='limit_bytes_out',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='limit_uptime',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='mikrotik',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='packets_in',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='packets_out',
        ),
        migrations.RemoveField(
            model_name='hotspotuser',
            name='session_time',
        ),
        migrations.RemoveField(
            model_name='mikrotikinterface',
            name='mikrotik',
        ),
        migrations.RemoveField(
            model_name='mikrotikqueue',
            name='burst_threshold',
        ),
        migrations.RemoveField(
            model_name='mikrotikqueue',
            name='burst_time',
        ),
        migrations.RemoveField(
            model_name='mikrotikqueue',
            name='mikrotik',
        ),
        migrations.RemoveField(
            model_name='mikrotikqueue',
            name='packet_mark',
        ),
        migrations.RemoveField(
            model_name='mikrotikqueue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='idle_time',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='last_connection',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='last_disconnection',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='mikrotik',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='packets_in',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='packets_out',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='service',
        ),
        migrations.RemoveField(
            model_name='pppoeuser',
            name='session_time',
        ),
        migrations.DeleteModel(
            name='MikrotikDevice',
        ),
    ]
