# Generated by Django 4.2.7 on 2026-01-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='router',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='router',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this router belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='core.company'),
        ),
        migrations.AlterField(
            model_name='hotspotuser',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='mikrotikinterface',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='mikrotikqueue',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='pppoeuser',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, help_text='Tenant schema name (auto-filled from company)', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='routerevent',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['company'], name='network_rou_company_e9c5cb_idx'),
        ),
    ]
