# Generated by Django 5.2.10 on 2026-01-22 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='router',
            name='network_rou_company_e9c5cb_idx',
        ),
        migrations.RemoveField(
            model_name='router',
            name='company',
        ),
        migrations.AddField(
            model_name='router',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name (denormalized from public schema)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='tenant_subdomain',
            field=models.CharField(blank=True, help_text='Tenant subdomain (denormalized from public schema)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['company_name'], name='network_rou_company_4379d8_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['tenant_subdomain'], name='network_rou_tenant__ce7ad7_idx'),
        ),
    ]
