# Generated by Django 4.2.7 on 2026-01-14 11:03

import apps.network.models.router_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalsystemsettings'),
        ('network', '0002_router_routerevent_remove_mikrotikdevice_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='shared_secret',
            field=models.CharField(default=apps.network.models.router_models.generate_shared_secret, help_text='RADIUS shared secret — used when configuring this router as a RADIUS client', max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='auth_key',
            field=models.CharField(default=apps.network.models.router_models.generate_auth_key, help_text='Auto-generated key used by router script to authenticate', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='company',
            field=models.ForeignKey(help_text='The ISP/company this router belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='core.company'),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Management IP — auto-filled on authentication', null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(blank=True, help_text='WAN MAC address (optional)', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(help_text='Friendly name for the router', max_length=255),
        ),
    ]
