# Generated by Django 5.2.10 on 2026-01-27 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('network', '0002_remove_router_network_rou_company_e9c5cb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_type', models.CharField(choices=[('basic', 'Basic Router'), ('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('isp', 'Full ISP (Hotspot + PPPoE)'), ('full_isp', 'Full ISP with OpenVPN')], max_length=20)),
                ('config_data', models.JSONField(default=dict, help_text='Configuration parameters')),
                ('config_script', models.TextField(help_text='Generated RouterOS script')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.CharField(blank=True, max_length=100, null=True)),
                ('schema_name', models.SlugField(blank=True, editable=False, max_length=63, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='connected_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='connected_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='config_type',
            field=models.CharField(choices=[('basic', 'Basic Router'), ('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('isp', 'Full ISP (Hotspot + PPPoE)'), ('full_isp', 'Full ISP with OpenVPN')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='enable_hotspot',
            field=models.BooleanField(default=True, help_text='Enable Hotspot service'),
        ),
        migrations.AddField(
            model_name='router',
            name='enable_openvpn',
            field=models.BooleanField(default=False, help_text='Enable OpenVPN client (for backhaul)'),
        ),
        migrations.AddField(
            model_name='router',
            name='enable_pppoe',
            field=models.BooleanField(default=True, help_text='Enable PPPoE service'),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_cookie_lifetime',
            field=models.CharField(default='4w2d', help_text='Hotspot cookie lifetime (e.g., 4w2d)', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_portal_url',
            field=models.URLField(default='https://app.yourisp.local', help_text='Hotspot captive portal URL'),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_ssl_cert',
            field=models.CharField(blank=True, help_text='SSL certificate name for Hotspot HTTPS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_subnet',
            field=models.CharField(default='172.19.0.0/16', help_text='Hotspot network subnet (e.g., 172.19.0.0/16)', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='lan_interfaces',
            field=models.CharField(default='ether2,ether3,ether4,ether5', help_text='Comma-separated LAN interfaces', max_length=200),
        ),
        migrations.AddField(
            model_name='router',
            name='lan_subnet',
            field=models.CharField(default='192.168.88.0/24', help_text='LAN network subnet (e.g., 192.168.88.0/24)', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_password',
            field=models.CharField(blank=True, help_text='OpenVPN password (auto-generated if empty)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_port',
            field=models.IntegerField(default=1194, help_text='OpenVPN server port'),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_server',
            field=models.CharField(default='vpn.yourisp.local', help_text='OpenVPN server address', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='openvpn_username',
            field=models.CharField(blank=True, help_text='OpenVPN username (auto-generated if empty)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='pppoe_pool',
            field=models.CharField(default='192.40.2.10-192.40.2.254', help_text='PPPoE IP pool range', max_length=50),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_port',
            field=models.IntegerField(default=1812, help_text='RADIUS authentication port'),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_server',
            field=models.GenericIPAddressField(blank=True, help_text='RADIUS server IP address', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='router',
            name='wan_interface',
            field=models.CharField(default='ether1', help_text='WAN interface name (e.g., ether1, sfp-sfpplus1)', max_length=50),
        ),
        migrations.AddField(
            model_name='routerevent',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='routerevent',
            name='event_type',
            field=models.CharField(choices=[('up', 'Router Online'), ('down', 'Router Offline'), ('reboot', 'Router Rebooted'), ('config_change', 'Configuration Changed'), ('warning', 'Warning'), ('error', 'Error'), ('maintenance', 'Maintenance Mode'), ('auth_success', 'Authenticated Successfully'), ('auth_key_regen', 'Auth Key Regenerated'), ('backup', 'Backup Created'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_enabled', 'User Enabled'), ('user_disabled', 'User Disabled'), ('queue_created', 'Queue Created'), ('queue_removed', 'Queue Removed'), ('interface_up', 'Interface Up'), ('interface_down', 'Interface Down'), ('config_sync', 'Configuration Synced'), ('script_executed', 'Script Executed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['router', 'status'], name='network_hot_router__59f438_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['last_seen'], name='network_hot_last_se_292ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['router', 'status'], name='network_ppp_router__6a97dd_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['last_seen'], name='network_ppp_last_se_1d61b8_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['config_type'], name='network_rou_config__bef5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='routerevent',
            index=models.Index(fields=['router', 'event_type'], name='network_rou_router__e3136f_idx'),
        ),
        migrations.AddIndex(
            model_name='routerevent',
            index=models.Index(fields=['created_at'], name='network_rou_created_380ae9_idx'),
        ),
        migrations.AddField(
            model_name='routerconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routerconfiguration',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='network.router'),
        ),
        migrations.AddField(
            model_name='routerconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='routerconfiguration',
            index=models.Index(fields=['router', 'is_active'], name='network_rou_router__38796c_idx'),
        ),
        migrations.AddIndex(
            model_name='routerconfiguration',
            index=models.Index(fields=['applied_at'], name='network_rou_applied_ba14a7_idx'),
        ),
    ]
