# Generated by Django 4.2.7 on 2026-03-02 09:30

import apps.network.models.router_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_routerconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='vpn_certificate',
            field=models.ForeignKey(blank=True, help_text='The active VPN certificate for this router', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_routers', to='vpn.vpncertificate'),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Static IP assigned in OpenVPN CCD (e.g. 10.8.0.55)', null=True, protocol='IPv4', unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this router was seen connected via VPN tunnel', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_provisioned',
            field=models.BooleanField(default=False, help_text='Whether VPN certificates and CCD have been provisioned'),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wan_interface',
            field=models.CharField(default='ether1', max_length=50),
        ),
        migrations.AddField(
            model_name='routerevent',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='network.ippool'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('RESERVED', 'Reserved'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='network.subnet'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='dns_servers',
            field=models.CharField(blank=True, default='8.8.8.8,8.8.4.4', max_length=200),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='end_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='name',
            field=models.CharField(help_text='Pool name (auto-generated from plan name if created via plan form)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='pool_type',
            field=models.CharField(choices=[('DHCP', 'DHCP Pool'), ('STATIC', 'Static Pool'), ('RESERVED', 'Reserved Pool'), ('PPPOE', 'PPPoE Pool')], default='PPPOE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='start_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='subnet',
            field=models.ForeignKey(blank=True, help_text='Optional parent subnet (for DHCP/Static pools)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='network.subnet'),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(blank=True, default='changeme', help_text='Auto-generated on save', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='router',
            name='api_port',
            field=models.PositiveIntegerField(default=8728),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_username',
            field=models.CharField(default='netily_api', max_length=100),
        ),
        migrations.AlterField(
            model_name='router',
            name='auth_key',
            field=models.CharField(default=apps.network.models.router_models.generate_auth_key, help_text="The key used in the 'One-Liner' script.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Management IP (VPN Address)', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(help_text="Friendly name (e.g. 'Site A Router')", max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='shared_secret',
            field=models.CharField(default=apps.network.models.router_models.generate_shared_secret, help_text='Secret shared between Router and RADIUS server', max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='routerevent',
            name='event_type',
            field=models.CharField(choices=[('up', 'Router Online'), ('down', 'Router Offline'), ('reboot', 'Router Rebooted'), ('config_change', 'Configuration Changed'), ('warning', 'Warning'), ('error', 'Error'), ('maintenance', 'Maintenance Mode'), ('auth_success', 'Authenticated Successfully'), ('auth_key_regen', 'Auth Key Regenerated'), ('backup', 'Backup Created'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_enabled', 'User Enabled'), ('user_disabled', 'User Disabled'), ('queue_created', 'Queue Created'), ('queue_removed', 'Queue Removed'), ('interface_up', 'Interface Up'), ('interface_down', 'Interface Down'), ('config_sync', 'Configuration Synced'), ('script_executed', 'Script Executed'), ('firewall_rule_added', 'Firewall Rule Added'), ('interface_enabled', 'Interface Enabled'), ('interface_disabled', 'Interface Disabled'), ('queue_enabled', 'Queue Enabled'), ('queue_disabled', 'Queue Disabled')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ippool',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['router', 'status'], name='network_hot_router__59f438_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_pool', 'status'], name='network_ipa_ip_pool_aab973_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['router', 'status'], name='network_ppp_router__6a97dd_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['tenant_subdomain'], name='network_rou_tenant__ce7ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='routerevent',
            index=models.Index(fields=['router', 'event_type'], name='network_rou_router__e3136f_idx'),
        ),
        migrations.AddIndex(
            model_name='routerevent',
            index=models.Index(fields=['created_at'], name='network_rou_created_380ae9_idx'),
        ),
        migrations.AddField(
            model_name='routerconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routerconfiguration',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='network.router'),
        ),
        migrations.AddField(
            model_name='routerconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ippool',
            name='schema_name',
        ),
        migrations.AddIndex(
            model_name='routerconfiguration',
            index=models.Index(fields=['router', 'is_active'], name='network_rou_router__38796c_idx'),
        ),
    ]
