# Generated by Django 5.2.10 on 2026-01-29 08:50

import apps.network.models.router_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_add_router_config_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotspotuser',
            name='network_hot_last_se_292ec0_idx',
        ),
        migrations.RemoveIndex(
            model_name='pppoeuser',
            name='network_ppp_last_se_1d61b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='router',
            name='network_rou_last_se_746cd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='router',
            name='network_rou_company_4379d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='router',
            name='network_rou_config__bef5b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='routerconfiguration',
            name='network_rou_applied_ba14a7_idx',
        ),
        migrations.AddField(
            model_name='router',
            name='dns_name',
            field=models.CharField(default='captive.netily.io', help_text='DNS name for the hotspot (e.g., login.wifi)', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='gateway_cidr',
            field=models.CharField(default='172.18.0.1/16', help_text='The main Gateway IP/Subnet (e.g., 172.18.0.1/16). Pool is calculated from this.', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_interfaces',
            field=models.JSONField(blank=True, default=list, help_text='List of interfaces assigned to the Hotspot Bridge'),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(blank=True, default='changeme', help_text='Auto-generated on save', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='router',
            name='api_port',
            field=models.PositiveIntegerField(default=8728),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_username',
            field=models.CharField(default='netily_api', max_length=100),
        ),
        migrations.AlterField(
            model_name='router',
            name='auth_key',
            field=models.CharField(default=apps.network.models.router_models.generate_auth_key, help_text="The key used in the 'One-Liner' script.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='config_type',
            field=models.CharField(choices=[('basic', 'Basic Router'), ('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('isp', 'Full ISP (Hotspot + PPPoE)'), ('full_isp', 'Full ISP with OpenVPN')], default='isp', max_length=20),
        ),
        migrations.AlterField(
            model_name='router',
            name='enable_hotspot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='enable_openvpn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='enable_pppoe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='hotspot_cookie_lifetime',
            field=models.CharField(default='4w2d', max_length=10),
        ),
        migrations.AlterField(
            model_name='router',
            name='hotspot_portal_url',
            field=models.URLField(default='https://app.yourisp.local'),
        ),
        migrations.AlterField(
            model_name='router',
            name='hotspot_ssl_cert',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='hotspot_subnet',
            field=models.CharField(default='172.19.0.0/16', max_length=20),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Management IP (VPN Address)', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='router',
            name='lan_interfaces',
            field=models.CharField(default='ether2,ether3', max_length=200),
        ),
        migrations.AlterField(
            model_name='router',
            name='lan_subnet',
            field=models.CharField(default='192.168.88.0/24', max_length=20),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(help_text="Friendly name (e.g. 'Site A Router')", max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='openvpn_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='openvpn_port',
            field=models.IntegerField(default=1194),
        ),
        migrations.AlterField(
            model_name='router',
            name='openvpn_server',
            field=models.CharField(default='vpn.yourisp.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='router',
            name='openvpn_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='pppoe_pool',
            field=models.CharField(default='192.40.2.10-192.40.2.254', max_length=50),
        ),
        migrations.AlterField(
            model_name='router',
            name='radius_port',
            field=models.IntegerField(default=1812),
        ),
        migrations.AlterField(
            model_name='router',
            name='radius_server',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='router',
            name='schema_name',
            field=models.SlugField(blank=True, editable=False, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='shared_secret',
            field=models.CharField(default=apps.network.models.router_models.generate_shared_secret, help_text='Secret shared between Router and RADIUS server', max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='router',
            name='tenant_subdomain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='wan_interface',
            field=models.CharField(default='ether1', max_length=50),
        ),
        migrations.AlterField(
            model_name='routerevent',
            name='event_type',
            field=models.CharField(choices=[('up', 'Router Online'), ('down', 'Router Offline'), ('reboot', 'Router Rebooted'), ('config_change', 'Configuration Changed'), ('warning', 'Warning'), ('error', 'Error'), ('maintenance', 'Maintenance Mode'), ('auth_success', 'Authenticated Successfully'), ('auth_key_regen', 'Auth Key Regenerated'), ('backup', 'Backup Created'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_enabled', 'User Enabled'), ('user_disabled', 'User Disabled'), ('queue_created', 'Queue Created'), ('queue_removed', 'Queue Removed'), ('interface_up', 'Interface Up'), ('interface_down', 'Interface Down'), ('config_sync', 'Configuration Synced'), ('script_executed', 'Script Executed'), ('firewall_rule_added', 'Firewall Rule Added'), ('interface_enabled', 'Interface Enabled'), ('interface_disabled', 'Interface Disabled'), ('queue_enabled', 'Queue Enabled'), ('queue_disabled', 'Queue Disabled')], max_length=50),
        ),
    ]
