# Generated by Django 4.2.7 on 2026-03-09 17:40

import apps.network.models.router_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_router_vpn_certificate_router_vpn_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(blank=True, default=apps.network.models.router_models.generate_api_password, help_text='Auto-generated on save (RouterOS-safe, max 20 chars)', max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='openvpn_server',
            field=models.CharField(default='vpn.netily.co.ke', max_length=100),
        ),
    ]
