# Generated by Django 5.2.10 on 2026-02-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_hotspotuser_network_hot_last_se_292ec0_idx_and_more'),
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='ca_certificate',
            field=models.TextField(blank=True, help_text="PEM content of ca.crt for this router's VPN", null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='client_certificate',
            field=models.TextField(blank=True, help_text='PEM content of client.crt', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='client_key',
            field=models.TextField(blank=True, help_text='PEM content of client.key (should be encrypted at rest)', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_certificate',
            field=models.ForeignKey(blank=True, help_text='The active VPN certificate for this router', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_routers', to='vpn.vpncertificate'),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Static IP assigned in OpenVPN CCD (e.g. 10.8.0.55)', null=True, protocol='IPv4', unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this router was seen connected via VPN tunnel', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_provisioned',
            field=models.BooleanField(default=False, help_text='Whether VPN certificates and CCD have been provisioned'),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
