# Generated by Django 5.2.10 on 2026-02-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_cloud_controller_vpn_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='last_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='pppoe_local_address',
            field=models.GenericIPAddressField(blank=True, default='192.40.2.1', help_text='PPPoE server local address (service-name gateway)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='router',
            name='provision_slug',
            field=models.SlugField(blank=True, help_text='Short URL-safe slug for magic-link downloads (auto-generated)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='routeros_version',
            field=models.CharField(blank=True, help_text='Detected RouterOS major version (6 or 7)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_certificate',
            field=models.TextField(blank=True, help_text='PEM content of SSL cert for hotspot HTTPS (e.g. *.yourisp.com)', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_passphrase',
            field=models.CharField(blank=True, default='', help_text='Passphrase for the SSL key (if encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_private_key',
            field=models.TextField(blank=True, help_text='PEM content of SSL private key', null=True),
        ),
    ]
