# Generated by Django 5.2.10 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_add_provisioning_fields_v4'),
    ]

    operations = [
        # Step 1: Remove old unique_together that uses ['subnet', 'name']
        migrations.AlterUniqueTogether(
            name='ippool',
            unique_together=set(),
        ),

        # Step 2: Remove schema_name field from IPPool (no longer needed with django-tenants)
        migrations.RemoveField(
            model_name='ippool',
            name='schema_name',
        ),

        # Step 3: Add the router FK (nullable for existing rows)
        migrations.AddField(
            model_name='ippool',
            name='router',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='The physical router (NAS) this pool exists on',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ip_pools',
                to='network.router',
            ),
        ),

        # Step 4: Make subnet optional (pools can exist without a subnet)
        migrations.AlterField(
            model_name='ippool',
            name='subnet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Optional parent subnet (for DHCP/Static pools)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pools',
                to='network.subnet',
            ),
        ),

        # Step 5: Add PPPOE to pool type choices
        migrations.AlterField(
            model_name='ippool',
            name='pool_type',
            field=models.CharField(
                choices=[
                    ('DHCP', 'DHCP Pool'),
                    ('STATIC', 'Static Pool'),
                    ('RESERVED', 'Reserved Pool'),
                    ('PPPOE', 'PPPoE Pool'),
                ],
                default='PPPOE',
                max_length=20,
            ),
        ),

        # Step 6: Update pool name help text
        migrations.AlterField(
            model_name='ippool',
            name='name',
            field=models.CharField(
                help_text='Pool name — must match the /ip pool name on the MikroTik router',
                max_length=100,
            ),
        ),

        # Step 7: Set new unique_together and ordering (now that router field exists)
        migrations.AlterUniqueTogether(
            name='ippool',
            unique_together={('router', 'name')},
        ),
        migrations.AlterModelOptions(
            name='ippool',
            options={
                'ordering': ['router', 'name'],
                'verbose_name': 'IP Pool',
                'verbose_name_plural': 'IP Pools',
            },
        ),
    ]
