# Generated by Django 5.2.10 on 2026-02-18 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_make_id_number_optional'),
        ('network', '0007_ipam_router_fk_pools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Customer currently holding this IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ips', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='broadcast_address',
            field=models.GenericIPAddressField(blank=True, help_text='Broadcast address (e.g. 10.50.3.255)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='cidr_prefix',
            field=models.IntegerField(blank=True, choices=[(24, '/24 — 254 usable IPs'), (25, '/25 — 126 usable IPs'), (26, '/26 — 62 usable IPs'), (27, '/27 — 30 usable IPs'), (28, '/28 — 14 usable IPs'), (29, '/29 — 6 usable IPs'), (30, '/30 — 2 usable IPs')], default=24, help_text='CIDR mask: /24=254 IPs, /25=126, /26=62, etc.', null=True),
        ),
        migrations.AddField(
            model_name='ippool',
            name='network_address',
            field=models.GenericIPAddressField(blank=True, help_text='Network address (e.g. 10.50.3.0)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='subnet_octet',
            field=models.IntegerField(blank=True, help_text='Third octet (0-255), e.g. 3 → 10.50.3.x', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='ippool',
            name='subnet_prefix',
            field=models.CharField(blank=True, choices=[('10.0', '10.0.x.x'), ('10.20', '10.20.x.x'), ('10.30', '10.30.x.x'), ('10.40', '10.40.x.x'), ('10.50', '10.50.x.x (Netily Standard)'), ('10.60', '10.60.x.x'), ('10.70', '10.70.x.x'), ('10.80', '10.80.x.x'), ('10.90', '10.90.x.x'), ('10.100', '10.100.x.x'), ('10.110', '10.110.x.x'), ('10.120', '10.120.x.x'), ('172.16', '172.16.x.x'), ('172.17', '172.17.x.x'), ('172.19', '172.19.x.x'), ('172.20', '172.20.x.x'), ('172.24', '172.24.x.x'), ('172.28', '172.28.x.x'), ('172.31', '172.31.x.x'), ('192.168.0', '192.168.0.x (⚠ Home conflict)'), ('192.168.1', '192.168.1.x (⚠ Home conflict)'), ('192.168.10', '192.168.10.x'), ('192.168.100', '192.168.100.x')], help_text='First two octets, e.g. 10.50 → 10.50.x.x', max_length=15),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('RESERVED', 'Reserved'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='network.subnet'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='dns_servers',
            field=models.CharField(blank=True, default='8.8.8.8,8.8.4.4', max_length=200),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='end_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='name',
            field=models.CharField(help_text='Pool name (auto-generated from plan name if created via plan form)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='start_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_pool', 'status'], name='network_ipa_ip_pool_aab973_idx'),
        ),
    ]
