# Generated by Django 5.2.10 on 2026-02-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_cloud_led_ipam_static_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ippool',
            options={'ordering': ['name'], 'verbose_name': 'IP Pool', 'verbose_name_plural': 'IP Pools'},
        ),
        migrations.AlterUniqueTogether(
            name='ippool',
            unique_together={('name',)},
        ),
    ]
