# Generated by Django 5.2.10 on 2026-02-20 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_ippool_remove_router_from_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='hotspot_base_ip',
            field=models.GenericIPAddressField(default='172.12.0.1', help_text='Gateway IP for the hotspot network (e.g., 172.12.0.1)'),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_subnet_cidr',
            field=models.IntegerField(default=16, help_text='CIDR prefix length for hotspot subnet (e.g., 16 = /16 = 65,534 hosts)', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
