# Generated by Django 5.2.10 on 2026-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_add_hotspot_ipam_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='announcement_text',
            field=models.CharField(blank=True, default='', help_text="Short banner message on the captive portal (e.g. 'Buy 24h for KES 50!')", max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_name',
            field=models.CharField(blank=True, default='', help_text="Display name on the captive portal (e.g. 'Mjengo Fast Wi-Fi')", max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='support_phone',
            field=models.CharField(blank=True, default='', help_text='Customer-care phone shown on captive portal', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='template_id',
            field=models.IntegerField(default=1, help_text='UI template for captive portal (1-7)'),
        ),
    ]
