# Generated by Django 5.2.10 on 2026-04-08 14:41

import apps.network.models.router_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_router_announcement_text_router_hotspot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='network.ippool'),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(blank=True, default=apps.network.models.router_models.generate_api_password, help_text='Auto-generated on save (RouterOS-safe, max 20 chars)', max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='openvpn_server',
            field=models.CharField(default='vpn.netily.co.ke', max_length=100),
        ),
    ]
