# Generated by Django 5.2.10 on 2026-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_ipaddress_ip_pool_alter_router_api_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='logo',
            field=models.ImageField(blank=True, help_text='ISP logo displayed on the captive portal', null=True, upload_to='router_logos/'),
        ),
    ]
