# Generated by Django 4.2.7 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_router_api_password_and_more'),
        ('network', '0012_alter_ipaddress_ip_pool_alter_router_api_password_and_more'),
    ]

    operations = [
    ]
