# Generated by Django 5.2.10 on 2026-05-29 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_add_router_logo'),
        ('vpn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='api_remote_port',
            field=models.PositiveIntegerField(blank=True, help_text='External port for remote API access via VPN gateway', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='winbox_remote_port',
            field=models.PositiveIntegerField(blank=True, help_text='External port for remote Winbox access via VPN gateway', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wireguard_private_key',
            field=models.TextField(blank=True, help_text="Router's WireGuard private key (stored server-side, injected into RSC)", null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='wireguard_public_key',
            field=models.CharField(blank=True, help_text="Router's WireGuard public key (registered as peer on server)", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='cidr_prefix',
            field=models.IntegerField(blank=True, choices=[(16, '/16 — 65,534 usable IPs'), (17, '/17 — 32,766 usable IPs'), (18, '/18 — 16,382 usable IPs'), (19, '/19 — 8,190 usable IPs'), (20, '/20 — 4,094 usable IPs'), (21, '/21 — 2,046 usable IPs'), (22, '/22 — 1,022 usable IPs'), (23, '/23 — 510 usable IPs'), (24, '/24 — 254 usable IPs'), (25, '/25 — 126 usable IPs'), (26, '/26 — 62 usable IPs'), (27, '/27 — 30 usable IPs'), (28, '/28 — 14 usable IPs'), (29, '/29 — 6 usable IPs'), (30, '/30 — 2 usable IPs')], default=24, help_text='CIDR mask: /16=65K IPs, /24=254 IPs, /25=126, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ca_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='client_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='client_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='vpn_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_routers', to='vpn.vpncertificate'),
        ),
        migrations.AlterField(
            model_name='router',
            name='vpn_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Static VPN IP assigned to this router (WireGuard AllowedIPs)', null=True, protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='vpn_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='vpn_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['winbox_remote_port'], name='network_rou_winbox__43f123_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['api_remote_port'], name='network_rou_api_rem_1c08dd_idx'),
        ),
    ]
