# Generated by Django 4.2.7 on 2026-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_router_api_remote_port_router_winbox_remote_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='hide_plan_speed',
            field=models.BooleanField(default=False, help_text='If true, hide download/upload speed info on captive portal plan cards'),
        ),
    ]
