# Generated by Django 4.2.7 on 2026-08-05 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0017_payment_service_type_and_more'),
        ('network', '0015_router_hide_plan_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly label, e.g. 'Living Room TV'", max_length=100)),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=10)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mikrotik_binding_id', models.CharField(blank=True, max_length=32)),
                ('queue_name', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_bindings', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_bindings', to='billing.hotspotplan')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_bindings', to='network.router')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['router', 'status'], name='network_ipb_router__19e734_idx'), models.Index(fields=['status', 'expires_at'], name='network_ipb_status_2f4908_idx')],
                'unique_together': {('router', 'mac_address')},
            },
        ),
    ]