# Generated by Django 4.2.7 on 2026-08-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_router_last_login_html_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='last_login_html_version',
            field=models.CharField(blank=True, help_text='LOGIN_HTML_VERSION stamp last confirmed served to this router', max_length=10, null=True),
        ),
    ]