# Generated by Django 4.2.7 on 2026-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_router_last_login_html_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='dns_name',
            field=models.CharField(blank=True, default='', help_text='Optional. Leave blank — RouterOS then redirects unauthenticated clients straight to its own gateway IP with zero DNS lookup. A custom hostname here must resolve or every captive-portal redirect stalls waiting on DNS timeout.', max_length=100),
        ),
    ]