# Generated by Django 4.2.7 on 2026-08-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_router_dns_name'),
        ('network', '0019_router_portal_font'),
    ]

    operations = [
    ]