# Generated by Django 5.2.10 on 2026-04-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('customers', '0002_make_id_number_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChurnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(db_index=True, max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_events', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_c_created_66ac98_idx'), models.Index(fields=['reason', 'created_at'], name='analytics_c_reason_609a38_idx')],
            },
        ),
    ]
