# Generated by Django 4.2.7 on 2026-01-19 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('usage', 'Usage Threshold'), ('speed', 'Speed Anomaly'), ('security', 'Security Alert'), ('device', 'Device Offline')], max_length=20)),
                ('alert_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('threshold_percentage', models.PositiveIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)])),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('threshold_unit', models.CharField(blank=True, choices=[('mbps', 'Mbps'), ('gb', 'GB'), ('%', 'Percentage')], max_length=10)),
                ('message', models.TextField()),
                ('triggered_value', models.FloatField(blank=True, null=True)),
                ('notify_customer', models.BooleanField(default=False)),
                ('notify_staff', models.BooleanField(default=True)),
                ('notification_methods', models.JSONField(default=list)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bandwidth Alert',
                'verbose_name_plural': 'Bandwidth Alerts',
                'ordering': ['-triggered_at', 'alert_level'],
            },
        ),
        migrations.CreateModel(
            name='BandwidthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('profile_type', models.CharField(choices=[('residential', 'Residential'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('hotspot', 'Hotspot')], default='residential', max_length=20)),
                ('download_speed', models.PositiveIntegerField(help_text='Download speed in Mbps')),
                ('upload_speed', models.PositiveIntegerField(help_text='Upload speed in Mbps')),
                ('data_cap', models.PositiveIntegerField(default=0, help_text='Monthly data cap in GB (0 for unlimited)')),
                ('burst_limit', models.PositiveIntegerField(default=0, help_text='Burst limit in Mbps (0 for no burst)')),
                ('burst_duration', models.PositiveIntegerField(default=0, help_text='Burst duration in seconds')),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guaranteed_min_speed', models.PositiveIntegerField(default=0, help_text='Guaranteed minimum speed in Mbps')),
                ('peak_hours_only', models.BooleanField(default=False)),
                ('peak_start_time', models.TimeField(blank=True, null=True)),
                ('peak_end_time', models.TimeField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bandwidth Profile',
                'verbose_name_plural': 'Bandwidth Profiles',
                'ordering': ['priority', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='TrafficRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('limit', 'Bandwidth Limit'), ('queue', 'Queue Rule'), ('filter', 'Packet Filter'), ('nat', 'NAT Rule'), ('mangle', 'Mangle Rule')], max_length=20)),
                ('priority_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, help_text='Destination IP address', null=True)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('any', 'Any')], default='any', max_length=10)),
                ('max_bandwidth', models.PositiveIntegerField(help_text='Maximum bandwidth in Kbps')),
                ('guaranteed_bandwidth', models.PositiveIntegerField(default=0, help_text='Guaranteed bandwidth in Kbps')),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('schedule_start', models.TimeField(blank=True, null=True)),
                ('schedule_end', models.TimeField(blank=True, null=True)),
                ('schedule_days', models.CharField(default='mon,tue,wed,thu,fri,sat,sun', max_length=50)),
                ('application_protocol', models.CharField(blank=True, max_length=50)),
                ('content_filter', models.TextField(blank=True)),
                ('target_device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_device_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Traffic Rule',
                'verbose_name_plural': 'Traffic Rules',
                'ordering': ['-priority_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('peak_download_speed', models.FloatField(default=0)),
                ('peak_upload_speed', models.FloatField(default=0)),
                ('peak_time', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('billing_cycle_id', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_usage', models.JSONField(default=dict)),
                ('hourly_peak', models.JSONField(default=dict)),
                ('is_over_limit', models.BooleanField(default=False)),
                ('overage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bandwidth_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bandwidth.bandwidthprofile')),
            ],
            options={
                'verbose_name': 'Data Usage',
                'verbose_name_plural': 'Data Usage Records',
                'ordering': ['-period_end', 'customer'],
            },
        ),
    ]
