# Generated by Django 4.2.7 on 2025-12-31 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandwidth', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_rules', to='core.company'),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speed_test_results', to='core.company'),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='datausage',
            name='bandwidth_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bandwidth.bandwidthprofile'),
        ),
        migrations.AddField(
            model_name='datausage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_usage', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='bandwidthprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_profiles', to='core.company'),
        ),
        migrations.AddField(
            model_name='bandwidthalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bandwidthalert',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_alerts', to='core.company'),
        ),
        migrations.AddField(
            model_name='bandwidthalert',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='datausage',
            unique_together={('customer', 'period_start', 'period_end')},
        ),
    ]
