# Generated by Django 5.2.10 on 2026-01-29 08:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('network', '0004_remove_hotspotuser_network_hot_last_se_292ec0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadGroupCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[(':=', 'Set (override)'), ('==', 'Equal'), ('!=', 'Not Equal'), ('>', 'Greater Than'), ('>=', 'Greater Than or Equal'), ('<', 'Less Than'), ('<=', 'Less Than or Equal'), ('=~', 'Regex Match'), ('!~', 'Regex Not Match'), ('=*', 'Attribute Exists'), ('!*', 'Attribute Not Exists')], default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Group Check',
                'verbose_name_plural': 'RADIUS Group Checks',
                'db_table': 'radgroupcheck',
            },
        ),
        migrations.CreateModel(
            name='RadGroupReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[('=', 'Add'), (':=', 'Set (override)'), ('+=', 'Append')], default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Group Reply',
                'verbose_name_plural': 'RADIUS Group Replies',
                'db_table': 'radgroupreply',
            },
        ),
        migrations.CreateModel(
            name='RadiusBandwidthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('download_speed', models.IntegerField(help_text='Download speed in kbps')),
                ('upload_speed', models.IntegerField(help_text='Upload speed in kbps')),
                ('burst_download', models.IntegerField(blank=True, help_text='Burst download in kbps', null=True)),
                ('burst_upload', models.IntegerField(blank=True, help_text='Burst upload in kbps', null=True)),
                ('burst_threshold', models.IntegerField(default=0, help_text='Burst threshold in kbps')),
                ('burst_time', models.IntegerField(default=0, help_text='Burst time in seconds')),
                ('priority', models.IntegerField(default=8, help_text='Queue priority (1=highest, 8=lowest)')),
                ('daily_limit_mb', models.BigIntegerField(blank=True, help_text='Daily data limit in MB', null=True)),
                ('monthly_limit_mb', models.BigIntegerField(blank=True, help_text='Monthly data limit in MB', null=True)),
                ('session_timeout', models.IntegerField(blank=True, help_text='Session timeout in seconds', null=True)),
                ('idle_timeout', models.IntegerField(blank=True, help_text='Idle timeout in seconds', null=True)),
                ('simultaneous_use', models.IntegerField(default=1, help_text='Max concurrent sessions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bandwidth Profile',
                'verbose_name_plural': 'Bandwidth Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nasname', models.CharField(help_text='IP address or hostname', max_length=128, unique=True)),
                ('shortname', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco'), ('ubiquiti', 'Ubiquiti'), ('other', 'Other')], default='other', max_length=30)),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.CharField(help_text='RADIUS shared secret', max_length=60)),
                ('server', models.CharField(blank=True, max_length=64, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nas_entry', to='network.router')),
            ],
            options={
                'verbose_name': 'NAS',
                'verbose_name_plural': 'NAS Entries',
                'db_table': 'nas',
            },
        ),
        migrations.CreateModel(
            name='RadPostAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('reply', models.CharField(max_length=32)),
                ('authdate', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('nasipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('callingstationid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'RADIUS Post-Auth Log',
                'verbose_name_plural': 'RADIUS Post-Auth Logs',
                'db_table': 'radpostauth',
                'indexes': [models.Index(fields=['username', 'authdate'], name='radpostauth_usernam_5db6e3_idx'), models.Index(fields=['reply', 'authdate'], name='radpostauth_reply_e0c854_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadUserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('groupname', models.CharField(db_index=True, max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'RADIUS User Group',
                'verbose_name_plural': 'RADIUS User Groups',
                'db_table': 'radusergroup',
                'unique_together': {('username', 'groupname')},
            },
        ),
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(db_index=True, max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('nasipaddress', models.GenericIPAddressField(db_index=True)),
                ('nasportid', models.CharField(blank=True, max_length=32, null=True)),
                ('nasporttype', models.CharField(blank=True, max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.IntegerField(blank=True, null=True)),
                ('acctsessiontime', models.BigIntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, max_length=128, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=128, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(blank=True, max_length=64, null=True)),
                ('callingstationid', models.CharField(blank=True, max_length=64, null=True)),
                ('acctterminatecause', models.CharField(blank=True, max_length=32, null=True)),
                ('servicetype', models.CharField(blank=True, max_length=32, null=True)),
                ('framedprotocol', models.CharField(blank=True, max_length=32, null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6address', models.CharField(blank=True, max_length=64, null=True)),
                ('framedipv6prefix', models.CharField(blank=True, max_length=64, null=True)),
                ('framedinterfaceid', models.CharField(blank=True, max_length=64, null=True)),
                ('delegatedipv6prefix', models.CharField(blank=True, max_length=64, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_sessions', to='customers.customer')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_sessions', to='network.router')),
            ],
            options={
                'verbose_name': 'RADIUS Accounting',
                'verbose_name_plural': 'RADIUS Accounting Records',
                'db_table': 'radacct',
                'indexes': [models.Index(fields=['username', 'acctstarttime'], name='radacct_usernam_8122be_idx'), models.Index(fields=['nasipaddress', 'acctstarttime'], name='radacct_nasipad_464e6e_idx'), models.Index(fields=['acctstoptime'], name='radacct_acctsto_d45083_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[(':=', 'Set (override)'), ('==', 'Equal'), ('!=', 'Not Equal'), ('>', 'Greater Than'), ('>=', 'Greater Than or Equal'), ('<', 'Less Than'), ('<=', 'Less Than or Equal'), ('=~', 'Regex Match'), ('!~', 'Regex Not Match'), ('=*', 'Attribute Exists'), ('!*', 'Attribute Not Exists')], default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_checks', to='customers.customer')),
            ],
            options={
                'verbose_name': 'RADIUS Check',
                'verbose_name_plural': 'RADIUS Checks',
                'db_table': 'radcheck',
                'indexes': [models.Index(fields=['username', 'attribute'], name='radcheck_usernam_d6e966_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[('=', 'Add'), (':=', 'Set (override)'), ('+=', 'Append')], default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_replies', to='customers.customer')),
            ],
            options={
                'verbose_name': 'RADIUS Reply',
                'verbose_name_plural': 'RADIUS Replies',
                'db_table': 'radreply',
                'indexes': [models.Index(fields=['username', 'attribute'], name='radreply_usernam_531b3d_idx')],
            },
        ),
    ]
