# Generated by Django 4.2.7 on 2026-03-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='acct_port',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='auth_port',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='container_status',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='deployment_mode',
        ),
        migrations.AddField(
            model_name='radacct',
            name='nasidentifier',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='radiustenantconfig',
            name='config_generated',
            field=models.BooleanField(default=False, help_text='Whether RADIUS config records have been generated'),
        ),
        migrations.AddIndex(
            model_name='radacct',
            index=models.Index(fields=['nasidentifier'], name='radacct_nasiden_008180_idx'),
        ),
    ]
