# Generated by Django 5.2.10 on 2026-01-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('radius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusTenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, help_text="Tenant schema name (e.g., 'tenant_myisp')", max_length=100, unique=True)),
                ('tenant_name', models.CharField(help_text='Human-readable tenant name', max_length=255)),
                ('radius_secret', models.CharField(blank=True, help_text='RADIUS shared secret for this tenant', max_length=128)),
                ('radius_port_auth', models.IntegerField(default=1812, help_text='Authentication port (for isolated mode)')),
                ('radius_port_acct', models.IntegerField(default=1813, help_text='Accounting port (for isolated mode)')),
                ('deployment_mode', models.CharField(choices=[('SHARED', 'Shared RADIUS (single instance)'), ('ISOLATED', 'Isolated RADIUS (per-tenant container)')], default='SHARED', help_text='RADIUS deployment mode for this tenant', max_length=20)),
                ('container_name', models.CharField(blank=True, help_text='Docker container name (isolated mode)', max_length=100)),
                ('container_status', models.CharField(blank=True, default='not_started', help_text='Container status', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('config_generated', models.BooleanField(default=False, help_text='Whether RADIUS config files have been generated')),
                ('last_config_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RADIUS Tenant Configuration',
                'verbose_name_plural': 'RADIUS Tenant Configurations',
            },
        ),
        migrations.CreateModel(
            name='CustomerRadiusCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='RADIUS username (used for PPPoE/Hotspot login)', max_length=64, unique=True)),
                ('password', models.CharField(help_text='RADIUS password (stored plaintext for FreeRADIUS)', max_length=253)),
                ('connection_type', models.CharField(choices=[('PPPOE', 'PPPoE'), ('HOTSPOT', 'Hotspot'), ('BOTH', 'PPPoE + Hotspot')], default='PPPOE', help_text='Type of RADIUS authentication', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this RADIUS account is active')),
                ('disabled_reason', models.CharField(blank=True, help_text='Reason for disabling (if disabled)', max_length=255)),
                ('static_ip', models.GenericIPAddressField(blank=True, help_text='Static IP to assign (optional)', null=True)),
                ('ip_pool', models.CharField(blank=True, help_text='IP pool name for dynamic assignment', max_length=64)),
                ('simultaneous_use', models.IntegerField(default=1, help_text='Max concurrent sessions allowed')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Account expiration date', null=True)),
                ('synced_to_radius', models.BooleanField(default=False, help_text='Whether synced to RADIUS tables')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bandwidth_profile', models.ForeignKey(blank=True, help_text='Bandwidth profile for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credentials', to='radius.radiusbandwidthprofile')),
                ('customer', models.OneToOneField(help_text='Customer this RADIUS account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='radius_credentials', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer RADIUS Credentials',
                'verbose_name_plural': 'Customer RADIUS Credentials',
            },
        ),
    ]
