# Generated by Django 4.2.7 on 2026-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_remove_radiustenantconfig_acct_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerradiuscredentials',
            name='subscription_activated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the current subscription period started. Resets on each renewal — used to calculate usage from zero.', null=True),
        ),
    ]
