# Generated by Django 5.2.10 on 2026-02-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_multi_tenant_radius'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerradiuscredentials',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer RADIUS Credentials', 'verbose_name_plural': 'Customer RADIUS Credentials'},
        ),
    ]
