# Generated by Django 5.2.10 on 2026-02-17 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_ipam_router_fk_pools'),
        ('radius', '0003_alter_customerradiuscredentials_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerradiuscredentials',
            name='router',
            field=models.ForeignKey(blank=True, help_text='The router (NAS) this customer connects through', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_customers', to='network.router'),
        ),
        migrations.AlterField(
            model_name='customerradiuscredentials',
            name='ip_pool',
            field=models.CharField(blank=True, help_text='IP pool name for dynamic assignment (Framed-Pool)', max_length=64),
        ),
    ]
