# Generated by Django 5.2.10 on 2026-02-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_cloud_led_ipam_static_ip'),
        ('radius', '0004_radius_router_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerradiuscredentials',
            name='assigned_ip_address',
            field=models.ForeignKey(blank=True, help_text='The specific IP address assigned from the pool (Cloud-Led IPAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_credentials', to='network.ipaddress'),
        ),
        migrations.AlterField(
            model_name='customerradiuscredentials',
            name='ip_pool',
            field=models.CharField(blank=True, help_text='IP pool name for dynamic assignment (Framed-Pool) — legacy, kept for backward compat', max_length=64),
        ),
        migrations.AlterField(
            model_name='customerradiuscredentials',
            name='static_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Static IP to assign (optional — legacy field, prefer assigned_ip_address)', null=True),
        ),
    ]
