# Generated by Django 5.2.10 on 2026-04-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_serviceconnection_billing_account_number_and_more'),
        ('network', '0012_alter_ipaddress_ip_pool_alter_router_api_password_and_more'),
        ('radius', '0005_cloud_led_ipam_static_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='container_status',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='deployment_mode',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='radius_port_acct',
        ),
        migrations.RemoveField(
            model_name='radiustenantconfig',
            name='radius_port_auth',
        ),
        migrations.AddField(
            model_name='customerradiuscredentials',
            name='subscription_activated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the current subscription period started. Resets on each renewal — used to calculate usage from zero.', null=True),
        ),
        migrations.AddField(
            model_name='radacct',
            name='nasidentifier',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customerradiuscredentials',
            name='assigned_ip_address',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The specific IP address assigned from the pool (Cloud-Led IPAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_credentials', to='network.ipaddress'),
        ),
        migrations.AlterField(
            model_name='customerradiuscredentials',
            name='customer',
            field=models.OneToOneField(db_constraint=False, help_text='Customer this RADIUS account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='radius_credentials', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerradiuscredentials',
            name='router',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The router (NAS) this customer connects through', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_customers', to='network.router'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='router',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nas_entry', to='network.router'),
        ),
        migrations.AlterField(
            model_name='radacct',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_sessions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='radacct',
            name='router',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_sessions', to='network.router'),
        ),
        migrations.AlterField(
            model_name='radcheck',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_checks', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='radiustenantconfig',
            name='config_generated',
            field=models.BooleanField(default=False, help_text='Whether RADIUS config records have been generated'),
        ),
        migrations.AlterField(
            model_name='radreply',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_replies', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='radacct',
            index=models.Index(fields=['nasidentifier'], name='radacct_nasiden_008180_idx'),
        ),
    ]
