# Generated by Django 5.2.10 on 2026-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0006_remove_radiustenantconfig_container_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusExpiryReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('customer_id', models.CharField(db_index=True, max_length=100)),
                ('interval_key', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expiry Reminder Log',
                'verbose_name_plural': 'Expiry Reminder Logs',
                'indexes': [models.Index(fields=['customer_id', 'expiration_date'], name='radius_radi_custome_75c79f_idx')],
                'unique_together': {('customer_id', 'interval_key', 'expiration_date')},
            },
        ),
    ]
