# Generated by Django 4.2.7 on 2026-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0003_customerradiuscredentials_subscription_activated_at'),
        ('radius', '0006_remove_radiustenantconfig_container_name_and_more'),
    ]

    operations = [
    ]
