# Generated by Django 4.2.7 on 2026-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0007_radiusexpiryreminderlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='radacct',
            index=models.Index(fields=['username', 'acctstoptime'], name='radacct_user_open_idx'),
        ),
    ]