# Generated by Django 4.2.7 on 2026-09-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0008_radacct_radacct_user_open_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerradiuscredentials',
            name='billing_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day-of-month this subscription originally started/paid on. Only used for CALENDAR_MONTH plans — keeps the renewal date fixed instead of drifting after a clamped short month.', null=True),
        ),
    ]