# Generated by Django 4.2.7 on 2026-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0009_customerradiuscredentials_billing_anchor_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusbandwidthprofile',
            name='fup_total_limit_bytes',
            field=models.BigIntegerField(blank=True, help_text='Pushed to MikroTik as Mikrotik-Total-Limit so the router enforces the FUP data cap natively, independent of Celery polling.', null=True),
        ),
    ]