# Generated by Django 4.2.7 on 2025-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='notificatio_is_acti_849c63_idx',
            old_name='notificatio_is_acti_af603c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_cd4f27_idx',
            old_name='notificatio_user_id_5b55eb_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_c384cf_idx',
            old_name='notificatio_status_46e970_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_sent_at_265656_idx',
            old_name='notificatio_sent_at_c7f54e_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_47102c_idx',
            old_name='notificatio_recipie_e8d7fa_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='notificatio_trigger_bf38a2_idx',
            old_name='notificatio_trigger_2a5a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='notificatio_notific_d9e94e_idx',
            old_name='notificatio_notific_9e698a_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='notificatio_is_acti_b2a982_idx',
            old_name='notificatio_is_acti_89c6af_idx',
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
